<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list, applicable only for radio lookups
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
	ut: 0 (default) returns all results, 1 returns unique texts (useful only if we don't care about ids, only text)
	json: 0 (default) returns HTML output for radio lookups, 1 forces json results for all including radio lookups
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	// drop-downs config
	$lookups = [
		'Estado_Conservacion' => [
		],
		'Estado_Prestable' => [
		],
		'Registros' => [
			'id_Estado_Conservacion' => [
				'parent_table' => 'Estado_Conservacion',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Conservacion`.`Descripcion`',
				'parent_from' => '`Estado_Conservacion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Estado_Prestable' => [
				'parent_table' => 'Estado_Prestable',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Prestable`.`Descripcion`',
				'parent_from' => '`Estado_Prestable` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Estado_Prestamo' => [
		],
		'Estado_Catalogacion' => [
		],
		'Editoriales' => [
		],
		'Catalogo' => [
			'Codigo_Registro' => [
				'parent_table' => 'Registros',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Registros`.`Codigo_de_Registro`',
				'parent_from' => '`Registros` LEFT JOIN `Estado_Conservacion` as Estado_Conservacion1 ON `Estado_Conservacion1`.`id`=`Registros`.`id_Estado_Conservacion` LEFT JOIN `Estado_Prestable` as Estado_Prestable1 ON `Estado_Prestable1`.`id`=`Registros`.`id_Estado_Prestable` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Cod_Barras' => [
				'parent_table' => 'Registros',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Registros`.`Codigo_Barras`',
				'parent_from' => '`Registros` LEFT JOIN `Estado_Conservacion` as Estado_Conservacion1 ON `Estado_Conservacion1`.`id`=`Registros`.`id_Estado_Conservacion` LEFT JOIN `Estado_Prestable` as Estado_Prestable1 ON `Estado_Prestable1`.`id`=`Registros`.`id_Estado_Prestable` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Tipo_Documento' => [
				'parent_table' => 'Tipo_Documento',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Documento`.`Descripcion`',
				'parent_from' => '`Tipo_Documento` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Estado_Catalogacion' => [
				'parent_table' => 'Estado_Catalogacion',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Catalogacion`.`Descripcion`',
				'parent_from' => '`Estado_Catalogacion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Id_Autoridad' => [
				'parent_table' => 'Autoridades',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Autoridades`.`Nombre`',
				'parent_from' => '`Autoridades` LEFT JOIN `Tipo_Autoridad` as Tipo_Autoridad1 ON `Tipo_Autoridad1`.`id`=`Autoridades`.`id_Tipo_autoridad` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Id_Lugar' => [
				'parent_table' => 'Lugares',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Lugares`.`Descripcion`',
				'parent_from' => '`Lugares` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Editorial' => [
				'parent_table' => 'Editoriales',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Editoriales`.`Nombre`',
				'parent_from' => '`Editoriales` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Materia_1' => [
				'parent_table' => 'Materias',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Materias`.`Descriptor`',
				'parent_from' => '`Materias` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Materia_2' => [
				'parent_table' => 'Materias',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Materias`.`Descriptor`',
				'parent_from' => '`Materias` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Materia_3' => [
				'parent_table' => 'Materias',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Materias`.`Descriptor`',
				'parent_from' => '`Materias` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Circulacion' => [
			'id_Usuario' => [
				'parent_table' => 'Usuarios',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Usuarios`.`Apellidos`) || CHAR_LENGTH(`Usuarios`.`Nombres`), CONCAT_WS(\'\', `Usuarios`.`Apellidos`, \', \', `Usuarios`.`Nombres`), \'\')',
				'parent_from' => '`Usuarios` LEFT JOIN `Tipo_Usuario` as Tipo_Usuario1 ON `Tipo_Usuario1`.`id`=`Usuarios`.`id_Tipo_usuario` LEFT JOIN `Estado_Suscripcion` as Estado_Suscripcion1 ON `Estado_Suscripcion1`.`id`=`Usuarios`.`id_Estado_suscripcion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Foto_Usuario' => [
				'parent_table' => 'Usuarios',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Usuarios`.`Foto`',
				'parent_from' => '`Usuarios` LEFT JOIN `Tipo_Usuario` as Tipo_Usuario1 ON `Tipo_Usuario1`.`id`=`Usuarios`.`id_Tipo_usuario` LEFT JOIN `Estado_Suscripcion` as Estado_Suscripcion1 ON `Estado_Suscripcion1`.`id`=`Usuarios`.`id_Estado_suscripcion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Tipo_usuario' => [
				'parent_table' => 'Tipo_Usuario',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Usuario`.`Descripcion`',
				'parent_from' => '`Tipo_Usuario` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Politica_pretamo' => [
				'parent_table' => 'Politica_de_Prestamos',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Politica_de_Prestamos`.`Duracion_Prestamo`) || CHAR_LENGTH(`Politica_de_Prestamos`.`Lim_Doc_Presado`), CONCAT_WS(\'\', `Politica_de_Prestamos`.`Duracion_Prestamo`, \' dias. L&#237;mite: \', `Politica_de_Prestamos`.`Lim_Doc_Presado`), \'\')',
				'parent_from' => '`Politica_de_Prestamos` LEFT JOIN `Tipo_Usuario` as Tipo_Usuario1 ON `Tipo_Usuario1`.`id`=`Politica_de_Prestamos`.`id_Tipo_usuario` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Politica_de_Prestamos`.`id_Tipo_documento` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Tipo_documento' => [
				'parent_table' => 'Tipo_Documento',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Documento`.`Descripcion`',
				'parent_from' => '`Tipo_Documento` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Registro' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS(\'\',   `Registros1`.`Codigo_de_Registro`), \'\')',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Libro_Prestado' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Catalogo`.`Titulo`',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Portada_libro' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Catalogo`.`Portada`',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Estado_prestamo' => [
				'parent_table' => 'Estado_Prestamo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Prestamo`.`Descripcion`',
				'parent_from' => '`Estado_Prestamo` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Ejemp_Disponibles' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Catalogo`.`Ejemplares`',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Item' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Catalogo`.`Item`',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Cod_Ejemplar' => [
				'parent_table' => 'Itemes',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Itemes`.`Cod_Ejemplar`',
				'parent_from' => '`Itemes` LEFT JOIN `Catalogo` as Catalogo1 ON `Catalogo1`.`id`=`Itemes`.`Cod_item` LEFT JOIN `Estado_Conservacion` as Estado_Conservacion1 ON `Estado_Conservacion1`.`id`=`Itemes`.`Estado_Conservacion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Tipo_Documento' => [
		],
		'Autoridades' => [
			'id_Tipo_autoridad' => [
				'parent_table' => 'Tipo_Autoridad',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Autoridad`.`Descripcion`',
				'parent_from' => '`Tipo_Autoridad` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Estado_Suscripcion' => [
		],
		'Usuarios' => [
			'id_Tipo_usuario' => [
				'parent_table' => 'Tipo_Usuario',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Usuario`.`Descripcion`',
				'parent_from' => '`Tipo_Usuario` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Estado_suscripcion' => [
				'parent_table' => 'Estado_Suscripcion',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Suscripcion`.`Descripcion`',
				'parent_from' => '`Estado_Suscripcion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Politica_de_Prestamos' => [
			'id_Tipo_usuario' => [
				'parent_table' => 'Tipo_Usuario',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Usuario`.`Descripcion`',
				'parent_from' => '`Tipo_Usuario` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'id_Tipo_documento' => [
				'parent_table' => 'Tipo_Documento',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Tipo_Documento`.`Descripcion`',
				'parent_from' => '`Tipo_Documento` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Lugares' => [
		],
		'Tipo_Autoridad' => [
		],
		'Tipo_Usuario' => [
		],
		'Materias' => [
		],
		'Itemes' => [
			'Cod_item' => [
				'parent_table' => 'Catalogo',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Catalogo`.`Item`',
				'parent_from' => '`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Estado_Conservacion' => [
				'parent_table' => 'Estado_Conservacion',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Estado_Conservacion`.`Descripcion`',
				'parent_from' => '`Estado_Conservacion` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
	];

	// XSS prevention
	$xss = new CI_Input(datalist_db_encoding);

	// receive and verify user input
	$table_name = Request::val('t');
	$field_name = Request::val('f');
	$search_id = makeSafe(from_utf8(Request::val('id')));
	$selected_text = from_utf8(Request::val('text'));
	$returnOptions = (Request::val('o') == 1 ? true : false);
	$page = intval(Request::val('p'));
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8(Request::val('s')));
	$uniqueText = Request::val('ut') ? true : false;
	$forceJson = Request::val('json') ? true : false;

	$res = null;

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm['access'] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = [];

	// search term provided?
	if($search_term) {
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])) {
		foreach($field['filterers'] as $filterer => $filterer_parent) {
			if($get = Request::val("filterer_{$filterer}", false))
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']) {
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id) {
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	$where = '';
	if(count($wheres)) {
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']) {
		$qm = []; $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)) {
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)) {
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where) {
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		} elseif($custom_where) {
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		} else {
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = [];
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])) {
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		} else {
			$count_query = '';
		}
	} else {
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id) {
		$combo->SelectedData = $search_id;
	} elseif($selected_text) {
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2 && !$forceJson) {
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions) {
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		} else {
			?>
				<span class="match-text" id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>">
			<?php
		}
	} else {
		/* return json */
		header('Content-type: application/json');

		/* if unique text (ut=1), we don't care about IDs and can group by text */
		if($uniqueText && !preg_match('/\bgroup by\b/i', $combo->Query)) {
			// do we have an order by?
			if(preg_match('/\border by\b/i', $combo->Query))
				$combo->Query = preg_replace('/\b(order by)\b/i', ' GROUP BY 2 $1', $combo->Query);
			else
				$combo->Query .= ' GROUP BY 2 ';
		}

		if(!preg_match('/ limit .+/i', $combo->Query)) {
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = [];

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text) {
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = ['id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text))];
		} else {
			/*
			 * in case we have a search term, show matches starting with it first,
			 * followed by those containing it.
			 * build a UNION query for that purpose
			 */
			if($search_term) {
				$query2 = $combo->Query;
				$query1 = str_replace(" like '%{$search_term}%'", " like '{$search_term}%'", $query2);
				$combo->Query = "({$query1}) UNION ({$query2})";
			}

			$eo = ['silentErrors' => true];

			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)) {
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']) {
					$prepared_data[] = ['id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>")];
				}

				$prepared_data[] = ['id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1]))];
			}
		}

		if(empty($prepared_data)) { $prepared_data[] = ['id' => '', 'text' => to_utf8($Translation['No matches found!'])]; }

		echo json_encode([
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3),
		]);
	}

