<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Autoridades.php');
	include_once(__DIR__ . '/Autoridades_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Autoridades');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Autoridades';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Autoridades`.`id`" => "id",
		"`Autoridades`.`Foto`" => "Foto",
		"IF(    CHAR_LENGTH(`Tipo_Autoridad1`.`Descripcion`), CONCAT_WS('',   `Tipo_Autoridad1`.`Descripcion`), '') /* Id Tipo autoridad */" => "id_Tipo_autoridad",
		"`Autoridades`.`Nombre`" => "Nombre",
		"`Autoridades`.`Fecha_Extrema`" => "Fecha_Extrema",
		"`Autoridades`.`Vease_Ademas`" => "Vease_Ademas",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Autoridades`.`id`',
		2 => 2,
		3 => '`Tipo_Autoridad1`.`Descripcion`',
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Autoridades`.`id`" => "id",
		"`Autoridades`.`Foto`" => "Foto",
		"IF(    CHAR_LENGTH(`Tipo_Autoridad1`.`Descripcion`), CONCAT_WS('',   `Tipo_Autoridad1`.`Descripcion`), '') /* Id Tipo autoridad */" => "id_Tipo_autoridad",
		"`Autoridades`.`Nombre`" => "Nombre",
		"`Autoridades`.`Fecha_Extrema`" => "Fecha_Extrema",
		"`Autoridades`.`Vease_Ademas`" => "Vease_Ademas",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Autoridades`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Tipo_Autoridad1`.`Descripcion`), CONCAT_WS('',   `Tipo_Autoridad1`.`Descripcion`), '') /* Id Tipo autoridad */" => "Id Tipo autoridad",
		"`Autoridades`.`Nombre`" => "Nombre",
		"`Autoridades`.`Fecha_Extrema`" => "Fecha Extrema",
		"`Autoridades`.`Vease_Ademas`" => "Vease Ademas",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Autoridades`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Tipo_Autoridad1`.`Descripcion`), CONCAT_WS('',   `Tipo_Autoridad1`.`Descripcion`), '') /* Id Tipo autoridad */" => "id_Tipo_autoridad",
		"`Autoridades`.`Nombre`" => "Nombre",
		"`Autoridades`.`Fecha_Extrema`" => "Fecha_Extrema",
		"`Autoridades`.`Vease_Ademas`" => "Vease_Ademas",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_Tipo_autoridad' => 'Id Tipo autoridad', ];

	$x->QueryFrom = "`Autoridades` LEFT JOIN `Tipo_Autoridad` as Tipo_Autoridad1 ON `Tipo_Autoridad1`.`id`=`Autoridades`.`id_Tipo_autoridad` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Autoridades_view.php';
	$x->TableTitle = 'Autoridades';
	$x->TableIcon = 'resources/table_icons/administrator.png';
	$x->PrimaryKey = '`Autoridades`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Foto', 'Id Tipo autoridad', 'Nombre', 'Fecha Extrema', 'Vease Ademas', ];
	$x->ColFieldName = ['Foto', 'id_Tipo_autoridad', 'Nombre', 'Fecha_Extrema', 'Vease_Ademas', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Autoridades_templateTV.html';
	$x->SelectedTemplate = 'templates/Autoridades_templateTVS.html';
	$x->TemplateDV = 'templates/Autoridades_templateDV.html';
	$x->TemplateDVP = 'templates/Autoridades_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Autoridades_init
	$render = true;
	if(function_exists('Autoridades_init')) {
		$args = [];
		$render = Autoridades_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Autoridades_header
	$headerCode = '';
	if(function_exists('Autoridades_header')) {
		$args = [];
		$headerCode = Autoridades_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Autoridades_footer
	$footerCode = '';
	if(function_exists('Autoridades_footer')) {
		$args = [];
		$footerCode = Autoridades_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
