<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Catalogo.php');
	include_once(__DIR__ . '/Catalogo_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Catalogo');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Catalogo';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Catalogo`.`id`" => "id",
		"`Catalogo`.`Portada`" => "Portada",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Codigo Registro */" => "Codigo_Registro",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_Barras`), CONCAT_WS('',   `Registros1`.`Codigo_Barras`), '') /* C&#243;digo de  Barras */" => "Cod_Barras",
		"`Catalogo`.`Item`" => "Item",
		"`Catalogo`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Catalogo`.`Tipo_Literatura`" => "Tipo_Literatura",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de Documento */" => "Tipo_Documento",
		"IF(    CHAR_LENGTH(`Estado_Catalogacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Catalogacion1`.`Descripcion`), '') /* Estado de Catalogacion */" => "id_Estado_Catalogacion",
		"`Catalogo`.`Signatura_Topografica`" => "Signatura_Topografica",
		"IF(    CHAR_LENGTH(`Autoridades1`.`Nombre`), CONCAT_WS('',   `Autoridades1`.`Nombre`), '') /* Autor */" => "Id_Autoridad",
		"`Catalogo`.`Titulo`" => "Titulo",
		"`Catalogo`.`Responsabilidades`" => "Responsabilidades",
		"`Catalogo`.`Edicion`" => "Edicion",
		"IF(    CHAR_LENGTH(`Lugares1`.`Descripcion`), CONCAT_WS('',   `Lugares1`.`Descripcion`), '') /* Lugar de Publicaci&#243;n */" => "Id_Lugar",
		"IF(    CHAR_LENGTH(`Editoriales1`.`Nombre`), CONCAT_WS('',   `Editoriales1`.`Nombre`), '') /* Editorial */" => "id_Editorial",
		"`Catalogo`.`Fecha_Publicacion`" => "Fecha_Publicacion",
		"`Catalogo`.`Desc_Fisica`" => "Desc_Fisica",
		"`Catalogo`.`Notas`" => "Notas",
		"IF(    CHAR_LENGTH(`Materias1`.`Descriptor`), CONCAT_WS('',   `Materias1`.`Descriptor`), '') /* Materia 1 */" => "Materia_1",
		"IF(    CHAR_LENGTH(`Materias2`.`Descriptor`), CONCAT_WS('',   `Materias2`.`Descriptor`), '') /* Materia 2 */" => "Materia_2",
		"IF(    CHAR_LENGTH(`Materias3`.`Descriptor`), CONCAT_WS('',   `Materias3`.`Descriptor`), '') /* Materia 3 */" => "Materia_3",
		"`Catalogo`.`Ejemplares`" => "Ejemplares",
		"if(`Catalogo`.`Fecha_Catalogacion`,date_format(`Catalogo`.`Fecha_Catalogacion`,'%m/%d/%Y'),'')" => "Fecha_Catalogacion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Catalogo`.`id`',
		2 => 2,
		3 => '`Registros1`.`Codigo_de_Registro`',
		4 => '`Registros1`.`Codigo_Barras`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`Tipo_Documento1`.`Descripcion`',
		9 => '`Estado_Catalogacion1`.`Descripcion`',
		10 => 10,
		11 => '`Autoridades1`.`Nombre`',
		12 => 12,
		13 => 13,
		14 => 14,
		15 => '`Lugares1`.`Descripcion`',
		16 => '`Editoriales1`.`Nombre`',
		17 => 17,
		18 => 18,
		19 => 19,
		20 => '`Materias1`.`Descriptor`',
		21 => '`Materias2`.`Descriptor`',
		22 => '`Materias3`.`Descriptor`',
		23 => '`Catalogo`.`Ejemplares`',
		24 => '`Catalogo`.`Fecha_Catalogacion`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Catalogo`.`id`" => "id",
		"`Catalogo`.`Portada`" => "Portada",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Codigo Registro */" => "Codigo_Registro",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_Barras`), CONCAT_WS('',   `Registros1`.`Codigo_Barras`), '') /* C&#243;digo de  Barras */" => "Cod_Barras",
		"`Catalogo`.`Item`" => "Item",
		"`Catalogo`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Catalogo`.`Tipo_Literatura`" => "Tipo_Literatura",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de Documento */" => "Tipo_Documento",
		"IF(    CHAR_LENGTH(`Estado_Catalogacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Catalogacion1`.`Descripcion`), '') /* Estado de Catalogacion */" => "id_Estado_Catalogacion",
		"`Catalogo`.`Signatura_Topografica`" => "Signatura_Topografica",
		"IF(    CHAR_LENGTH(`Autoridades1`.`Nombre`), CONCAT_WS('',   `Autoridades1`.`Nombre`), '') /* Autor */" => "Id_Autoridad",
		"`Catalogo`.`Titulo`" => "Titulo",
		"`Catalogo`.`Responsabilidades`" => "Responsabilidades",
		"`Catalogo`.`Edicion`" => "Edicion",
		"IF(    CHAR_LENGTH(`Lugares1`.`Descripcion`), CONCAT_WS('',   `Lugares1`.`Descripcion`), '') /* Lugar de Publicaci&#243;n */" => "Id_Lugar",
		"IF(    CHAR_LENGTH(`Editoriales1`.`Nombre`), CONCAT_WS('',   `Editoriales1`.`Nombre`), '') /* Editorial */" => "id_Editorial",
		"`Catalogo`.`Fecha_Publicacion`" => "Fecha_Publicacion",
		"`Catalogo`.`Desc_Fisica`" => "Desc_Fisica",
		"`Catalogo`.`Notas`" => "Notas",
		"IF(    CHAR_LENGTH(`Materias1`.`Descriptor`), CONCAT_WS('',   `Materias1`.`Descriptor`), '') /* Materia 1 */" => "Materia_1",
		"IF(    CHAR_LENGTH(`Materias2`.`Descriptor`), CONCAT_WS('',   `Materias2`.`Descriptor`), '') /* Materia 2 */" => "Materia_2",
		"IF(    CHAR_LENGTH(`Materias3`.`Descriptor`), CONCAT_WS('',   `Materias3`.`Descriptor`), '') /* Materia 3 */" => "Materia_3",
		"`Catalogo`.`Ejemplares`" => "Ejemplares",
		"if(`Catalogo`.`Fecha_Catalogacion`,date_format(`Catalogo`.`Fecha_Catalogacion`,'%m/%d/%Y'),'')" => "Fecha_Catalogacion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Catalogo`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Codigo Registro */" => "Codigo Registro",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_Barras`), CONCAT_WS('',   `Registros1`.`Codigo_Barras`), '') /* C&#243;digo de  Barras */" => "C&#243;digo de  Barras",
		"`Catalogo`.`Item`" => "Item",
		"`Catalogo`.`Cod_Ejemplar`" => "Cod Ejemplar",
		"`Catalogo`.`Tipo_Literatura`" => "Tipo de Literatura",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de Documento */" => "Tipo de Documento",
		"IF(    CHAR_LENGTH(`Estado_Catalogacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Catalogacion1`.`Descripcion`), '') /* Estado de Catalogacion */" => "Estado de Catalogacion",
		"`Catalogo`.`Signatura_Topografica`" => "Signatura Topografica",
		"IF(    CHAR_LENGTH(`Autoridades1`.`Nombre`), CONCAT_WS('',   `Autoridades1`.`Nombre`), '') /* Autor */" => "Autor",
		"`Catalogo`.`Titulo`" => "Titulo",
		"`Catalogo`.`Responsabilidades`" => "Responsabilidades",
		"`Catalogo`.`Edicion`" => "Edicion",
		"IF(    CHAR_LENGTH(`Lugares1`.`Descripcion`), CONCAT_WS('',   `Lugares1`.`Descripcion`), '') /* Lugar de Publicaci&#243;n */" => "Lugar de Publicaci&#243;n",
		"IF(    CHAR_LENGTH(`Editoriales1`.`Nombre`), CONCAT_WS('',   `Editoriales1`.`Nombre`), '') /* Editorial */" => "Editorial",
		"`Catalogo`.`Fecha_Publicacion`" => "Fecha de Publicacion",
		"`Catalogo`.`Desc_Fisica`" => "Descripci&#243;n Fisica",
		"`Catalogo`.`Notas`" => "Notas",
		"IF(    CHAR_LENGTH(`Materias1`.`Descriptor`), CONCAT_WS('',   `Materias1`.`Descriptor`), '') /* Materia 1 */" => "Materia 1",
		"IF(    CHAR_LENGTH(`Materias2`.`Descriptor`), CONCAT_WS('',   `Materias2`.`Descriptor`), '') /* Materia 2 */" => "Materia 2",
		"IF(    CHAR_LENGTH(`Materias3`.`Descriptor`), CONCAT_WS('',   `Materias3`.`Descriptor`), '') /* Materia 3 */" => "Materia 3",
		"`Catalogo`.`Ejemplares`" => "Ejemplares",
		"`Catalogo`.`Fecha_Catalogacion`" => "Fecha de Catalogaci&#243;n",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Catalogo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Codigo Registro */" => "Codigo_Registro",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_Barras`), CONCAT_WS('',   `Registros1`.`Codigo_Barras`), '') /* C&#243;digo de  Barras */" => "Cod_Barras",
		"`Catalogo`.`Item`" => "Item",
		"`Catalogo`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Catalogo`.`Tipo_Literatura`" => "Tipo_Literatura",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de Documento */" => "Tipo_Documento",
		"IF(    CHAR_LENGTH(`Estado_Catalogacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Catalogacion1`.`Descripcion`), '') /* Estado de Catalogacion */" => "id_Estado_Catalogacion",
		"`Catalogo`.`Signatura_Topografica`" => "Signatura_Topografica",
		"IF(    CHAR_LENGTH(`Autoridades1`.`Nombre`), CONCAT_WS('',   `Autoridades1`.`Nombre`), '') /* Autor */" => "Id_Autoridad",
		"`Catalogo`.`Titulo`" => "Titulo",
		"`Catalogo`.`Responsabilidades`" => "Responsabilidades",
		"`Catalogo`.`Edicion`" => "Edicion",
		"IF(    CHAR_LENGTH(`Lugares1`.`Descripcion`), CONCAT_WS('',   `Lugares1`.`Descripcion`), '') /* Lugar de Publicaci&#243;n */" => "Id_Lugar",
		"IF(    CHAR_LENGTH(`Editoriales1`.`Nombre`), CONCAT_WS('',   `Editoriales1`.`Nombre`), '') /* Editorial */" => "id_Editorial",
		"`Catalogo`.`Fecha_Publicacion`" => "Fecha_Publicacion",
		"`Catalogo`.`Desc_Fisica`" => "Desc_Fisica",
		"`Catalogo`.`Notas`" => "Notas",
		"IF(    CHAR_LENGTH(`Materias1`.`Descriptor`), CONCAT_WS('',   `Materias1`.`Descriptor`), '') /* Materia 1 */" => "Materia_1",
		"IF(    CHAR_LENGTH(`Materias2`.`Descriptor`), CONCAT_WS('',   `Materias2`.`Descriptor`), '') /* Materia 2 */" => "Materia_2",
		"IF(    CHAR_LENGTH(`Materias3`.`Descriptor`), CONCAT_WS('',   `Materias3`.`Descriptor`), '') /* Materia 3 */" => "Materia_3",
		"`Catalogo`.`Ejemplares`" => "Ejemplares",
		"if(`Catalogo`.`Fecha_Catalogacion`,date_format(`Catalogo`.`Fecha_Catalogacion`,'%m/%d/%Y'),'')" => "Fecha_Catalogacion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Codigo_Registro' => 'Codigo Registro', 'Tipo_Documento' => 'Tipo de Documento', 'id_Estado_Catalogacion' => 'Estado de Catalogacion', 'Id_Autoridad' => 'Autor', 'Id_Lugar' => 'Lugar de Publicaci&#243;n', 'id_Editorial' => 'Editorial', 'Materia_1' => 'Materia 1', 'Materia_2' => 'Materia 2', 'Materia_3' => 'Materia 3', ];

	$x->QueryFrom = "`Catalogo` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo`.`Codigo_Registro` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Catalogo`.`Tipo_Documento` LEFT JOIN `Estado_Catalogacion` as Estado_Catalogacion1 ON `Estado_Catalogacion1`.`id`=`Catalogo`.`id_Estado_Catalogacion` LEFT JOIN `Autoridades` as Autoridades1 ON `Autoridades1`.`id`=`Catalogo`.`Id_Autoridad` LEFT JOIN `Lugares` as Lugares1 ON `Lugares1`.`id`=`Catalogo`.`Id_Lugar` LEFT JOIN `Editoriales` as Editoriales1 ON `Editoriales1`.`id`=`Catalogo`.`id_Editorial` LEFT JOIN `Materias` as Materias1 ON `Materias1`.`id`=`Catalogo`.`Materia_1` LEFT JOIN `Materias` as Materias2 ON `Materias2`.`id`=`Catalogo`.`Materia_2` LEFT JOIN `Materias` as Materias3 ON `Materias3`.`id`=`Catalogo`.`Materia_3` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Catalogo_view.php';
	$x->TableTitle = 'Catalogo';
	$x->TableIcon = 'resources/table_icons/book_add.png';
	$x->PrimaryKey = '`Catalogo`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Portada', 'Codigo Registro', 'C&#243;digo de  Barras', 'Item', 'Cod Ejemplar', 'Tipo de Literatura', 'Tipo de Documento', 'Estado de Catalogacion', 'Signatura Topografica', 'Autor', 'Titulo', 'Responsabilidades', 'Edicion', 'Lugar de Publicaci&#243;n', 'Editorial', 'Fecha de Publicacion', 'Descripci&#243;n Fisica', 'Notas', 'Materia 1', 'Materia 2', 'Materia 3', 'Ejemplares', 'Fecha de Catalogaci&#243;n', ];
	$x->ColFieldName = ['Portada', 'Codigo_Registro', 'Cod_Barras', 'Item', 'Cod_Ejemplar', 'Tipo_Literatura', 'Tipo_Documento', 'id_Estado_Catalogacion', 'Signatura_Topografica', 'Id_Autoridad', 'Titulo', 'Responsabilidades', 'Edicion', 'Id_Lugar', 'id_Editorial', 'Fecha_Publicacion', 'Desc_Fisica', 'Notas', 'Materia_1', 'Materia_2', 'Materia_3', 'Ejemplares', 'Fecha_Catalogacion', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Catalogo_templateTV.html';
	$x->SelectedTemplate = 'templates/Catalogo_templateTVS.html';
	$x->TemplateDV = 'templates/Catalogo_templateDV.html';
	$x->TemplateDVP = 'templates/Catalogo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Catalogo_init
	$render = true;
	if(function_exists('Catalogo_init')) {
		$args = [];
		$render = Catalogo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Catalogo_header
	$headerCode = '';
	if(function_exists('Catalogo_header')) {
		$args = [];
		$headerCode = Catalogo_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Catalogo_footer
	$footerCode = '';
	if(function_exists('Catalogo_footer')) {
		$args = [];
		$footerCode = Catalogo_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
