<?php

// Data functions (insert, update, delete, form) for table Catalogo

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function Catalogo_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Catalogo');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Portada' => Request::fileUpload('Portada', [
			'maxSize' => 102400000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Catalogo', 'Portada', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Catalogo', 'Portada', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Catalogo', 'Portada', Request::val('SelectedID'));
			},
		]),
		'Codigo_Registro' => Request::lookup('Codigo_Registro', ''),
		'Cod_Barras' => Request::lookup('Codigo_Registro'),
		'Item' => Request::val('Item', ''),
		'Cod_Ejemplar' => Request::val('Cod_Ejemplar', ''),
		'Tipo_Literatura' => Request::val('Tipo_Literatura', ''),
		'Tipo_Documento' => Request::lookup('Tipo_Documento', ''),
		'id_Estado_Catalogacion' => Request::lookup('id_Estado_Catalogacion', ''),
		'Signatura_Topografica' => Request::val('Signatura_Topografica', ''),
		'Id_Autoridad' => Request::lookup('Id_Autoridad', ''),
		'Titulo' => Request::val('Titulo', ''),
		'Responsabilidades' => Request::val('Responsabilidades', ''),
		'Edicion' => Request::val('Edicion', ''),
		'Id_Lugar' => Request::lookup('Id_Lugar', ''),
		'id_Editorial' => Request::lookup('id_Editorial', ''),
		'Fecha_Publicacion' => Request::val('Fecha_Publicacion', ''),
		'Desc_Fisica' => Request::val('Desc_Fisica', ''),
		'Notas' => br2nl(Request::val('Notas', '')),
		'Materia_1' => Request::lookup('Materia_1', ''),
		'Materia_2' => Request::lookup('Materia_2', ''),
		'Materia_3' => Request::lookup('Materia_3', ''),
		'Ejemplares' => Request::val('Ejemplares', ''),
		'Fecha_Catalogacion' => Request::dateComponents('Fecha_Catalogacion', ''),
	];


	// hook: Catalogo_before_insert
	if(function_exists('Catalogo_before_insert')) {
		$args = [];
		if(!Catalogo_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Catalogo', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Catalogo', $recID, calculated_fields()['Catalogo']);

	// hook: Catalogo_after_insert
	if(function_exists('Catalogo_after_insert')) {
		$res = sql("SELECT * FROM `Catalogo` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Catalogo_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Catalogo', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Catalogo_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Catalogo_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Catalogo_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Catalogo', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Catalogo_before_delete
	if(function_exists('Catalogo_before_delete')) {
		$args = [];
		if(!Catalogo_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Circulacion
	$res = sql("SELECT `id` FROM `Catalogo` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Circulacion` WHERE `Libro_Prestado`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Catalogo_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Catalogo_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Itemes
	$res = sql("SELECT `id` FROM `Catalogo` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Itemes` WHERE `Cod_item`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Itemes', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Itemes', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Catalogo_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Catalogo_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Catalogo` WHERE `id`='{$selected_id}'", $eo);

	// hook: Catalogo_after_delete
	if(function_exists('Catalogo_after_delete')) {
		$args = [];
		Catalogo_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Catalogo' AND `pkValue`='{$selected_id}'", $eo);
}

function Catalogo_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Catalogo', $selected_id, 'edit')) return false;

	$data = [
		'Portada' => Request::fileUpload('Portada', [
			'maxSize' => 102400000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Catalogo', 'Portada', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Catalogo', 'Portada', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Catalogo', 'Portada', $selected_id);
			},
		]),
		'Codigo_Registro' => Request::lookup('Codigo_Registro', ''),
		'Cod_Barras' => Request::lookup('Codigo_Registro'),
		'Item' => Request::val('Item', ''),
		'Cod_Ejemplar' => Request::val('Cod_Ejemplar', ''),
		'Tipo_Literatura' => Request::val('Tipo_Literatura', ''),
		'Tipo_Documento' => Request::lookup('Tipo_Documento', ''),
		'id_Estado_Catalogacion' => Request::lookup('id_Estado_Catalogacion', ''),
		'Signatura_Topografica' => Request::val('Signatura_Topografica', ''),
		'Id_Autoridad' => Request::lookup('Id_Autoridad', ''),
		'Titulo' => Request::val('Titulo', ''),
		'Responsabilidades' => Request::val('Responsabilidades', ''),
		'Edicion' => Request::val('Edicion', ''),
		'Id_Lugar' => Request::lookup('Id_Lugar', ''),
		'id_Editorial' => Request::lookup('id_Editorial', ''),
		'Fecha_Publicacion' => Request::val('Fecha_Publicacion', ''),
		'Desc_Fisica' => Request::val('Desc_Fisica', ''),
		'Notas' => br2nl(Request::val('Notas', '')),
		'Materia_1' => Request::lookup('Materia_1', ''),
		'Materia_2' => Request::lookup('Materia_2', ''),
		'Materia_3' => Request::lookup('Materia_3', ''),
		'Ejemplares' => Request::val('Ejemplares', ''),
		'Fecha_Catalogacion' => Request::dateComponents('Fecha_Catalogacion', ''),
	];

	// get existing values
	$old_data = getRecord('Catalogo', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Catalogo_before_update
	if(function_exists('Catalogo_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Catalogo_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Catalogo', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Catalogo_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Catalogo', $data['selectedID'], calculated_fields()['Catalogo']);

	// hook: Catalogo_after_update
	if(function_exists('Catalogo_after_update')) {
		$res = sql("SELECT * FROM `Catalogo` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Catalogo_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Catalogo' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Catalogo_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Catalogo');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_Codigo_Registro = Request::val('filterer_Codigo_Registro');
	$filterer_Tipo_Documento = Request::val('filterer_Tipo_Documento');
	$filterer_id_Estado_Catalogacion = Request::val('filterer_id_Estado_Catalogacion');
	$filterer_Id_Autoridad = Request::val('filterer_Id_Autoridad');
	$filterer_Id_Lugar = Request::val('filterer_Id_Lugar');
	$filterer_id_Editorial = Request::val('filterer_id_Editorial');
	$filterer_Materia_1 = Request::val('filterer_Materia_1');
	$filterer_Materia_2 = Request::val('filterer_Materia_2');
	$filterer_Materia_3 = Request::val('filterer_Materia_3');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Codigo_Registro
	$combo_Codigo_Registro = new DataCombo;
	// combobox: Tipo_Literatura
	$combo_Tipo_Literatura = new Combo;
	$combo_Tipo_Literatura->ListType = 0;
	$combo_Tipo_Literatura->MultipleSeparator = ', ';
	$combo_Tipo_Literatura->ListBoxHeight = 10;
	$combo_Tipo_Literatura->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Catalogo.Tipo_Literatura.csv')) {
		$Tipo_Literatura_data = addslashes(implode('', @file(__DIR__ . '/hooks/Catalogo.Tipo_Literatura.csv')));
		$combo_Tipo_Literatura->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Tipo_Literatura_data))));
		$combo_Tipo_Literatura->ListData = $combo_Tipo_Literatura->ListItem;
	} else {
		$combo_Tipo_Literatura->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Monograf&#237;a;;Publicacion Peri&#243;dica;;No Convencional"))));
		$combo_Tipo_Literatura->ListData = $combo_Tipo_Literatura->ListItem;
	}
	$combo_Tipo_Literatura->SelectName = 'Tipo_Literatura';
	// combobox: Tipo_Documento
	$combo_Tipo_Documento = new DataCombo;
	// combobox: id_Estado_Catalogacion
	$combo_id_Estado_Catalogacion = new DataCombo;
	// combobox: Id_Autoridad
	$combo_Id_Autoridad = new DataCombo;
	// combobox: Id_Lugar
	$combo_Id_Lugar = new DataCombo;
	// combobox: id_Editorial
	$combo_id_Editorial = new DataCombo;
	// combobox: Materia_1
	$combo_Materia_1 = new DataCombo;
	// combobox: Materia_2
	$combo_Materia_2 = new DataCombo;
	// combobox: Materia_3
	$combo_Materia_3 = new DataCombo;
	// combobox: Fecha_Catalogacion
	$combo_Fecha_Catalogacion = new DateCombo;
	$combo_Fecha_Catalogacion->DateFormat = "mdy";
	$combo_Fecha_Catalogacion->MinYear = defined('Catalogo.Fecha_Catalogacion.MinYear') ? constant('Catalogo.Fecha_Catalogacion.MinYear') : 1900;
	$combo_Fecha_Catalogacion->MaxYear = defined('Catalogo.Fecha_Catalogacion.MaxYear') ? constant('Catalogo.Fecha_Catalogacion.MaxYear') : 2100;
	$combo_Fecha_Catalogacion->DefaultDate = parseMySQLDate('', '');
	$combo_Fecha_Catalogacion->MonthNames = $Translation['month names'];
	$combo_Fecha_Catalogacion->NamePrefix = 'Fecha_Catalogacion';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Catalogo' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Catalogo' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Catalogo` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Catalogo_view.php', false);
		}
		$combo_Codigo_Registro->SelectedData = $row['Codigo_Registro'];
		$combo_Tipo_Literatura->SelectedData = $row['Tipo_Literatura'];
		$combo_Tipo_Documento->SelectedData = $row['Tipo_Documento'];
		$combo_id_Estado_Catalogacion->SelectedData = $row['id_Estado_Catalogacion'];
		$combo_Id_Autoridad->SelectedData = $row['Id_Autoridad'];
		$combo_Id_Lugar->SelectedData = $row['Id_Lugar'];
		$combo_id_Editorial->SelectedData = $row['id_Editorial'];
		$combo_Materia_1->SelectedData = $row['Materia_1'];
		$combo_Materia_2->SelectedData = $row['Materia_2'];
		$combo_Materia_3->SelectedData = $row['Materia_3'];
		$combo_Fecha_Catalogacion->DefaultDate = $row['Fecha_Catalogacion'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Codigo_Registro->SelectedData = $filterer_Codigo_Registro;
		$combo_Tipo_Literatura->SelectedText = (isset($filterField[1]) && $filterField[1] == '7' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
		$combo_Tipo_Documento->SelectedData = $filterer_Tipo_Documento;
		$combo_id_Estado_Catalogacion->SelectedData = $filterer_id_Estado_Catalogacion;
		$combo_Id_Autoridad->SelectedData = $filterer_Id_Autoridad;
		$combo_Id_Lugar->SelectedData = $filterer_Id_Lugar;
		$combo_id_Editorial->SelectedData = $filterer_id_Editorial;
		$combo_Materia_1->SelectedData = $filterer_Materia_1;
		$combo_Materia_2->SelectedData = $filterer_Materia_2;
		$combo_Materia_3->SelectedData = $filterer_Materia_3;
	}
	$combo_Codigo_Registro->HTML = '<span id="Codigo_Registro-container' . $rnd1 . '"></span><input type="hidden" name="Codigo_Registro" id="Codigo_Registro' . $rnd1 . '" value="' . html_attr($combo_Codigo_Registro->SelectedData) . '">';
	$combo_Codigo_Registro->MatchText = '<span id="Codigo_Registro-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Codigo_Registro" id="Codigo_Registro' . $rnd1 . '" value="' . html_attr($combo_Codigo_Registro->SelectedData) . '">';
	$combo_Tipo_Literatura->Render();
	$combo_Tipo_Documento->HTML = '<span id="Tipo_Documento-container' . $rnd1 . '"></span><input type="hidden" name="Tipo_Documento" id="Tipo_Documento' . $rnd1 . '" value="' . html_attr($combo_Tipo_Documento->SelectedData) . '">';
	$combo_Tipo_Documento->MatchText = '<span id="Tipo_Documento-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Tipo_Documento" id="Tipo_Documento' . $rnd1 . '" value="' . html_attr($combo_Tipo_Documento->SelectedData) . '">';
	$combo_id_Estado_Catalogacion->HTML = '<span id="id_Estado_Catalogacion-container' . $rnd1 . '"></span><input type="hidden" name="id_Estado_Catalogacion" id="id_Estado_Catalogacion' . $rnd1 . '" value="' . html_attr($combo_id_Estado_Catalogacion->SelectedData) . '">';
	$combo_id_Estado_Catalogacion->MatchText = '<span id="id_Estado_Catalogacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Estado_Catalogacion" id="id_Estado_Catalogacion' . $rnd1 . '" value="' . html_attr($combo_id_Estado_Catalogacion->SelectedData) . '">';
	$combo_Id_Autoridad->HTML = '<span id="Id_Autoridad-container' . $rnd1 . '"></span><input type="hidden" name="Id_Autoridad" id="Id_Autoridad' . $rnd1 . '" value="' . html_attr($combo_Id_Autoridad->SelectedData) . '">';
	$combo_Id_Autoridad->MatchText = '<span id="Id_Autoridad-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Id_Autoridad" id="Id_Autoridad' . $rnd1 . '" value="' . html_attr($combo_Id_Autoridad->SelectedData) . '">';
	$combo_Id_Lugar->HTML = '<span id="Id_Lugar-container' . $rnd1 . '"></span><input type="hidden" name="Id_Lugar" id="Id_Lugar' . $rnd1 . '" value="' . html_attr($combo_Id_Lugar->SelectedData) . '">';
	$combo_Id_Lugar->MatchText = '<span id="Id_Lugar-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Id_Lugar" id="Id_Lugar' . $rnd1 . '" value="' . html_attr($combo_Id_Lugar->SelectedData) . '">';
	$combo_id_Editorial->HTML = '<span id="id_Editorial-container' . $rnd1 . '"></span><input type="hidden" name="id_Editorial" id="id_Editorial' . $rnd1 . '" value="' . html_attr($combo_id_Editorial->SelectedData) . '">';
	$combo_id_Editorial->MatchText = '<span id="id_Editorial-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Editorial" id="id_Editorial' . $rnd1 . '" value="' . html_attr($combo_id_Editorial->SelectedData) . '">';
	$combo_Materia_1->HTML = '<span id="Materia_1-container' . $rnd1 . '"></span><input type="hidden" name="Materia_1" id="Materia_1' . $rnd1 . '" value="' . html_attr($combo_Materia_1->SelectedData) . '">';
	$combo_Materia_1->MatchText = '<span id="Materia_1-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Materia_1" id="Materia_1' . $rnd1 . '" value="' . html_attr($combo_Materia_1->SelectedData) . '">';
	$combo_Materia_2->HTML = '<span id="Materia_2-container' . $rnd1 . '"></span><input type="hidden" name="Materia_2" id="Materia_2' . $rnd1 . '" value="' . html_attr($combo_Materia_2->SelectedData) . '">';
	$combo_Materia_2->MatchText = '<span id="Materia_2-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Materia_2" id="Materia_2' . $rnd1 . '" value="' . html_attr($combo_Materia_2->SelectedData) . '">';
	$combo_Materia_3->HTML = '<span id="Materia_3-container' . $rnd1 . '"></span><input type="hidden" name="Materia_3" id="Materia_3' . $rnd1 . '" value="' . html_attr($combo_Materia_3->SelectedData) . '">';
	$combo_Materia_3->MatchText = '<span id="Materia_3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Materia_3" id="Materia_3' . $rnd1 . '" value="' . html_attr($combo_Materia_3->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Codigo_Registro__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Codigo_Registro'] : htmlspecialchars($filterer_Codigo_Registro, ENT_QUOTES)); ?>"};
		AppGini.current_Tipo_Documento__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Tipo_Documento'] : htmlspecialchars($filterer_Tipo_Documento, ENT_QUOTES)); ?>"};
		AppGini.current_id_Estado_Catalogacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Estado_Catalogacion'] : htmlspecialchars($filterer_id_Estado_Catalogacion, ENT_QUOTES)); ?>"};
		AppGini.current_Id_Autoridad__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Id_Autoridad'] : htmlspecialchars($filterer_Id_Autoridad, ENT_QUOTES)); ?>"};
		AppGini.current_Id_Lugar__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Id_Lugar'] : htmlspecialchars($filterer_Id_Lugar, ENT_QUOTES)); ?>"};
		AppGini.current_id_Editorial__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Editorial'] : htmlspecialchars($filterer_id_Editorial, ENT_QUOTES)); ?>"};
		AppGini.current_Materia_1__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Materia_1'] : htmlspecialchars($filterer_Materia_1, ENT_QUOTES)); ?>"};
		AppGini.current_Materia_2__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Materia_2'] : htmlspecialchars($filterer_Materia_2, ENT_QUOTES)); ?>"};
		AppGini.current_Materia_3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Materia_3'] : htmlspecialchars($filterer_Materia_3, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Codigo_Registro_reload__RAND__) == 'function') Codigo_Registro_reload__RAND__();
				if(typeof(Tipo_Documento_reload__RAND__) == 'function') Tipo_Documento_reload__RAND__();
				if(typeof(id_Estado_Catalogacion_reload__RAND__) == 'function') id_Estado_Catalogacion_reload__RAND__();
				if(typeof(Id_Autoridad_reload__RAND__) == 'function') Id_Autoridad_reload__RAND__();
				if(typeof(Id_Lugar_reload__RAND__) == 'function') Id_Lugar_reload__RAND__();
				if(typeof(id_Editorial_reload__RAND__) == 'function') id_Editorial_reload__RAND__();
				if(typeof(Materia_1_reload__RAND__) == 'function') Materia_1_reload__RAND__();
				if(typeof(Materia_2_reload__RAND__) == 'function') Materia_2_reload__RAND__();
				if(typeof(Materia_3_reload__RAND__) == 'function') Materia_3_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Codigo_Registro_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Codigo_Registro-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Codigo_Registro__RAND__.value, t: 'Catalogo', f: 'Codigo_Registro' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Codigo_Registro"]').val(resp.results[0].id);
							$j('[id=Codigo_Registro-container-readonly__RAND__]').html('<span class="match-text" id="Codigo_Registro-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Registros_view_parent]').hide(); } else { $j('.btn[id=Registros_view_parent]').show(); }


							if(typeof(Codigo_Registro_update_autofills__RAND__) == 'function') Codigo_Registro_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Codigo_Registro' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Codigo_Registro__RAND__.value = e.added.id;
				AppGini.current_Codigo_Registro__RAND__.text = e.added.text;
				$j('[name="Codigo_Registro"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Registros_view_parent]').hide(); } else { $j('.btn[id=Registros_view_parent]').show(); }


				if(typeof(Codigo_Registro_update_autofills__RAND__) == 'function') Codigo_Registro_update_autofills__RAND__();
			});

			if(!$j("#Codigo_Registro-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Codigo_Registro__RAND__.value, t: 'Catalogo', f: 'Codigo_Registro' },
					success: function(resp) {
						$j('[name="Codigo_Registro"]').val(resp.results[0].id);
						$j('[id=Codigo_Registro-container-readonly__RAND__]').html('<span class="match-text" id="Codigo_Registro-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Registros_view_parent]').hide(); } else { $j('.btn[id=Registros_view_parent]').show(); }

						if(typeof(Codigo_Registro_update_autofills__RAND__) == 'function') Codigo_Registro_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Codigo_Registro__RAND__.value, t: 'Catalogo', f: 'Codigo_Registro' },
				success: function(resp) {
					$j('[id=Codigo_Registro-container__RAND__], [id=Codigo_Registro-container-readonly__RAND__]').html('<span class="match-text" id="Codigo_Registro-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Registros_view_parent]').hide(); } else { $j('.btn[id=Registros_view_parent]').show(); }

					if(typeof(Codigo_Registro_update_autofills__RAND__) == 'function') Codigo_Registro_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Tipo_Documento_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Tipo_Documento-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Tipo_Documento__RAND__.value, t: 'Catalogo', f: 'Tipo_Documento' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Tipo_Documento"]').val(resp.results[0].id);
							$j('[id=Tipo_Documento-container-readonly__RAND__]').html('<span class="match-text" id="Tipo_Documento-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


							if(typeof(Tipo_Documento_update_autofills__RAND__) == 'function') Tipo_Documento_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Tipo_Documento' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Tipo_Documento__RAND__.value = e.added.id;
				AppGini.current_Tipo_Documento__RAND__.text = e.added.text;
				$j('[name="Tipo_Documento"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


				if(typeof(Tipo_Documento_update_autofills__RAND__) == 'function') Tipo_Documento_update_autofills__RAND__();
			});

			if(!$j("#Tipo_Documento-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Tipo_Documento__RAND__.value, t: 'Catalogo', f: 'Tipo_Documento' },
					success: function(resp) {
						$j('[name="Tipo_Documento"]').val(resp.results[0].id);
						$j('[id=Tipo_Documento-container-readonly__RAND__]').html('<span class="match-text" id="Tipo_Documento-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

						if(typeof(Tipo_Documento_update_autofills__RAND__) == 'function') Tipo_Documento_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Tipo_Documento__RAND__.value, t: 'Catalogo', f: 'Tipo_Documento' },
				success: function(resp) {
					$j('[id=Tipo_Documento-container__RAND__], [id=Tipo_Documento-container-readonly__RAND__]').html('<span class="match-text" id="Tipo_Documento-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

					if(typeof(Tipo_Documento_update_autofills__RAND__) == 'function') Tipo_Documento_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Estado_Catalogacion_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Estado_Catalogacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Estado_Catalogacion__RAND__.value, t: 'Catalogo', f: 'id_Estado_Catalogacion' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Estado_Catalogacion"]').val(resp.results[0].id);
							$j('[id=id_Estado_Catalogacion-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_Catalogacion-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Catalogacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Catalogacion_view_parent]').show(); }


							if(typeof(id_Estado_Catalogacion_update_autofills__RAND__) == 'function') id_Estado_Catalogacion_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'id_Estado_Catalogacion' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Estado_Catalogacion__RAND__.value = e.added.id;
				AppGini.current_id_Estado_Catalogacion__RAND__.text = e.added.text;
				$j('[name="id_Estado_Catalogacion"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Catalogacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Catalogacion_view_parent]').show(); }


				if(typeof(id_Estado_Catalogacion_update_autofills__RAND__) == 'function') id_Estado_Catalogacion_update_autofills__RAND__();
			});

			if(!$j("#id_Estado_Catalogacion-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Estado_Catalogacion__RAND__.value, t: 'Catalogo', f: 'id_Estado_Catalogacion' },
					success: function(resp) {
						$j('[name="id_Estado_Catalogacion"]').val(resp.results[0].id);
						$j('[id=id_Estado_Catalogacion-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_Catalogacion-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Catalogacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Catalogacion_view_parent]').show(); }

						if(typeof(id_Estado_Catalogacion_update_autofills__RAND__) == 'function') id_Estado_Catalogacion_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Estado_Catalogacion__RAND__.value, t: 'Catalogo', f: 'id_Estado_Catalogacion' },
				success: function(resp) {
					$j('[id=id_Estado_Catalogacion-container__RAND__], [id=id_Estado_Catalogacion-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_Catalogacion-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Catalogacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Catalogacion_view_parent]').show(); }

					if(typeof(id_Estado_Catalogacion_update_autofills__RAND__) == 'function') id_Estado_Catalogacion_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Id_Autoridad_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Id_Autoridad-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Id_Autoridad__RAND__.value, t: 'Catalogo', f: 'Id_Autoridad' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Id_Autoridad"]').val(resp.results[0].id);
							$j('[id=Id_Autoridad-container-readonly__RAND__]').html('<span class="match-text" id="Id_Autoridad-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Autoridades_view_parent]').hide(); } else { $j('.btn[id=Autoridades_view_parent]').show(); }


							if(typeof(Id_Autoridad_update_autofills__RAND__) == 'function') Id_Autoridad_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Id_Autoridad' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Id_Autoridad__RAND__.value = e.added.id;
				AppGini.current_Id_Autoridad__RAND__.text = e.added.text;
				$j('[name="Id_Autoridad"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Autoridades_view_parent]').hide(); } else { $j('.btn[id=Autoridades_view_parent]').show(); }


				if(typeof(Id_Autoridad_update_autofills__RAND__) == 'function') Id_Autoridad_update_autofills__RAND__();
			});

			if(!$j("#Id_Autoridad-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Id_Autoridad__RAND__.value, t: 'Catalogo', f: 'Id_Autoridad' },
					success: function(resp) {
						$j('[name="Id_Autoridad"]').val(resp.results[0].id);
						$j('[id=Id_Autoridad-container-readonly__RAND__]').html('<span class="match-text" id="Id_Autoridad-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Autoridades_view_parent]').hide(); } else { $j('.btn[id=Autoridades_view_parent]').show(); }

						if(typeof(Id_Autoridad_update_autofills__RAND__) == 'function') Id_Autoridad_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Id_Autoridad__RAND__.value, t: 'Catalogo', f: 'Id_Autoridad' },
				success: function(resp) {
					$j('[id=Id_Autoridad-container__RAND__], [id=Id_Autoridad-container-readonly__RAND__]').html('<span class="match-text" id="Id_Autoridad-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Autoridades_view_parent]').hide(); } else { $j('.btn[id=Autoridades_view_parent]').show(); }

					if(typeof(Id_Autoridad_update_autofills__RAND__) == 'function') Id_Autoridad_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Id_Lugar_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Id_Lugar-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Id_Lugar__RAND__.value, t: 'Catalogo', f: 'Id_Lugar' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Id_Lugar"]').val(resp.results[0].id);
							$j('[id=Id_Lugar-container-readonly__RAND__]').html('<span class="match-text" id="Id_Lugar-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lugares_view_parent]').hide(); } else { $j('.btn[id=Lugares_view_parent]').show(); }


							if(typeof(Id_Lugar_update_autofills__RAND__) == 'function') Id_Lugar_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Id_Lugar' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Id_Lugar__RAND__.value = e.added.id;
				AppGini.current_Id_Lugar__RAND__.text = e.added.text;
				$j('[name="Id_Lugar"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lugares_view_parent]').hide(); } else { $j('.btn[id=Lugares_view_parent]').show(); }


				if(typeof(Id_Lugar_update_autofills__RAND__) == 'function') Id_Lugar_update_autofills__RAND__();
			});

			if(!$j("#Id_Lugar-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Id_Lugar__RAND__.value, t: 'Catalogo', f: 'Id_Lugar' },
					success: function(resp) {
						$j('[name="Id_Lugar"]').val(resp.results[0].id);
						$j('[id=Id_Lugar-container-readonly__RAND__]').html('<span class="match-text" id="Id_Lugar-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lugares_view_parent]').hide(); } else { $j('.btn[id=Lugares_view_parent]').show(); }

						if(typeof(Id_Lugar_update_autofills__RAND__) == 'function') Id_Lugar_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Id_Lugar__RAND__.value, t: 'Catalogo', f: 'Id_Lugar' },
				success: function(resp) {
					$j('[id=Id_Lugar-container__RAND__], [id=Id_Lugar-container-readonly__RAND__]').html('<span class="match-text" id="Id_Lugar-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Lugares_view_parent]').hide(); } else { $j('.btn[id=Lugares_view_parent]').show(); }

					if(typeof(Id_Lugar_update_autofills__RAND__) == 'function') Id_Lugar_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Editorial_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Editorial-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Editorial__RAND__.value, t: 'Catalogo', f: 'id_Editorial' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Editorial"]').val(resp.results[0].id);
							$j('[id=id_Editorial-container-readonly__RAND__]').html('<span class="match-text" id="id_Editorial-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Editoriales_view_parent]').hide(); } else { $j('.btn[id=Editoriales_view_parent]').show(); }


							if(typeof(id_Editorial_update_autofills__RAND__) == 'function') id_Editorial_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'id_Editorial' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Editorial__RAND__.value = e.added.id;
				AppGini.current_id_Editorial__RAND__.text = e.added.text;
				$j('[name="id_Editorial"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Editoriales_view_parent]').hide(); } else { $j('.btn[id=Editoriales_view_parent]').show(); }


				if(typeof(id_Editorial_update_autofills__RAND__) == 'function') id_Editorial_update_autofills__RAND__();
			});

			if(!$j("#id_Editorial-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Editorial__RAND__.value, t: 'Catalogo', f: 'id_Editorial' },
					success: function(resp) {
						$j('[name="id_Editorial"]').val(resp.results[0].id);
						$j('[id=id_Editorial-container-readonly__RAND__]').html('<span class="match-text" id="id_Editorial-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Editoriales_view_parent]').hide(); } else { $j('.btn[id=Editoriales_view_parent]').show(); }

						if(typeof(id_Editorial_update_autofills__RAND__) == 'function') id_Editorial_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Editorial__RAND__.value, t: 'Catalogo', f: 'id_Editorial' },
				success: function(resp) {
					$j('[id=id_Editorial-container__RAND__], [id=id_Editorial-container-readonly__RAND__]').html('<span class="match-text" id="id_Editorial-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Editoriales_view_parent]').hide(); } else { $j('.btn[id=Editoriales_view_parent]').show(); }

					if(typeof(id_Editorial_update_autofills__RAND__) == 'function') id_Editorial_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Materia_1_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Materia_1-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Materia_1__RAND__.value, t: 'Catalogo', f: 'Materia_1' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Materia_1"]').val(resp.results[0].id);
							$j('[id=Materia_1-container-readonly__RAND__]').html('<span class="match-text" id="Materia_1-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


							if(typeof(Materia_1_update_autofills__RAND__) == 'function') Materia_1_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Materia_1' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Materia_1__RAND__.value = e.added.id;
				AppGini.current_Materia_1__RAND__.text = e.added.text;
				$j('[name="Materia_1"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


				if(typeof(Materia_1_update_autofills__RAND__) == 'function') Materia_1_update_autofills__RAND__();
			});

			if(!$j("#Materia_1-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Materia_1__RAND__.value, t: 'Catalogo', f: 'Materia_1' },
					success: function(resp) {
						$j('[name="Materia_1"]').val(resp.results[0].id);
						$j('[id=Materia_1-container-readonly__RAND__]').html('<span class="match-text" id="Materia_1-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

						if(typeof(Materia_1_update_autofills__RAND__) == 'function') Materia_1_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Materia_1__RAND__.value, t: 'Catalogo', f: 'Materia_1' },
				success: function(resp) {
					$j('[id=Materia_1-container__RAND__], [id=Materia_1-container-readonly__RAND__]').html('<span class="match-text" id="Materia_1-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

					if(typeof(Materia_1_update_autofills__RAND__) == 'function') Materia_1_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Materia_2_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Materia_2-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Materia_2__RAND__.value, t: 'Catalogo', f: 'Materia_2' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Materia_2"]').val(resp.results[0].id);
							$j('[id=Materia_2-container-readonly__RAND__]').html('<span class="match-text" id="Materia_2-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


							if(typeof(Materia_2_update_autofills__RAND__) == 'function') Materia_2_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Materia_2' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Materia_2__RAND__.value = e.added.id;
				AppGini.current_Materia_2__RAND__.text = e.added.text;
				$j('[name="Materia_2"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


				if(typeof(Materia_2_update_autofills__RAND__) == 'function') Materia_2_update_autofills__RAND__();
			});

			if(!$j("#Materia_2-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Materia_2__RAND__.value, t: 'Catalogo', f: 'Materia_2' },
					success: function(resp) {
						$j('[name="Materia_2"]').val(resp.results[0].id);
						$j('[id=Materia_2-container-readonly__RAND__]').html('<span class="match-text" id="Materia_2-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

						if(typeof(Materia_2_update_autofills__RAND__) == 'function') Materia_2_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Materia_2__RAND__.value, t: 'Catalogo', f: 'Materia_2' },
				success: function(resp) {
					$j('[id=Materia_2-container__RAND__], [id=Materia_2-container-readonly__RAND__]').html('<span class="match-text" id="Materia_2-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

					if(typeof(Materia_2_update_autofills__RAND__) == 'function') Materia_2_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Materia_3_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Materia_3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Materia_3__RAND__.value, t: 'Catalogo', f: 'Materia_3' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Materia_3"]').val(resp.results[0].id);
							$j('[id=Materia_3-container-readonly__RAND__]').html('<span class="match-text" id="Materia_3-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


							if(typeof(Materia_3_update_autofills__RAND__) == 'function') Materia_3_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Catalogo', f: 'Materia_3' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Materia_3__RAND__.value = e.added.id;
				AppGini.current_Materia_3__RAND__.text = e.added.text;
				$j('[name="Materia_3"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }


				if(typeof(Materia_3_update_autofills__RAND__) == 'function') Materia_3_update_autofills__RAND__();
			});

			if(!$j("#Materia_3-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Materia_3__RAND__.value, t: 'Catalogo', f: 'Materia_3' },
					success: function(resp) {
						$j('[name="Materia_3"]').val(resp.results[0].id);
						$j('[id=Materia_3-container-readonly__RAND__]').html('<span class="match-text" id="Materia_3-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

						if(typeof(Materia_3_update_autofills__RAND__) == 'function') Materia_3_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Materia_3__RAND__.value, t: 'Catalogo', f: 'Materia_3' },
				success: function(resp) {
					$j('[id=Materia_3-container__RAND__], [id=Materia_3-container-readonly__RAND__]').html('<span class="match-text" id="Materia_3-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Materias_view_parent]').hide(); } else { $j('.btn[id=Materias_view_parent]').show(); }

					if(typeof(Materia_3_update_autofills__RAND__) == 'function') Materia_3_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Catalogo_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Catalogo_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Catalogo details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Catalogo_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Catalogo_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Catalogo_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Portada').replaceWith('<div class=\"form-control-static\" id=\"Portada\">' + (jQuery('#Portada').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Codigo_Registro').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Codigo_Registro_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Item').replaceWith('<div class=\"form-control-static\" id=\"Item\">' + (jQuery('#Item').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Cod_Ejemplar').replaceWith('<div class=\"form-control-static\" id=\"Cod_Ejemplar\">' + (jQuery('#Cod_Ejemplar').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Tipo_Literatura').replaceWith('<div class=\"form-control-static\" id=\"Tipo_Literatura\">' + (jQuery('#Tipo_Literatura').val() || '') + '</div>'); jQuery('#Tipo_Literatura-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Tipo_Documento').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Tipo_Documento_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Estado_Catalogacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Estado_Catalogacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Signatura_Topografica').replaceWith('<div class=\"form-control-static\" id=\"Signatura_Topografica\">' + (jQuery('#Signatura_Topografica').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Id_Autoridad').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Id_Autoridad_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Titulo').replaceWith('<div class=\"form-control-static\" id=\"Titulo\">' + (jQuery('#Titulo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Responsabilidades').replaceWith('<div class=\"form-control-static\" id=\"Responsabilidades\">' + (jQuery('#Responsabilidades').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Edicion').replaceWith('<div class=\"form-control-static\" id=\"Edicion\">' + (jQuery('#Edicion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Id_Lugar').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Id_Lugar_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Editorial').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Editorial_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Fecha_Publicacion').replaceWith('<div class=\"form-control-static\" id=\"Fecha_Publicacion\">' + (jQuery('#Fecha_Publicacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Desc_Fisica').replaceWith('<div class=\"form-control-static\" id=\"Desc_Fisica\">' + (jQuery('#Desc_Fisica').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Notas').replaceWith('<div class=\"form-control-static\" id=\"Notas\">' + (jQuery('#Notas').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Materia_1').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Materia_1_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Materia_2').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Materia_2_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Materia_3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Materia_3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Ejemplares').replaceWith('<div class=\"form-control-static\" id=\"Ejemplares\">' + (jQuery('#Ejemplares').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Fecha_Catalogacion').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Fecha_CatalogacionDay, #Fecha_CatalogacionMonth, #Fecha_CatalogacionYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Codigo_Registro)%%>', $combo_Codigo_Registro->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Codigo_Registro)%%>', $combo_Codigo_Registro->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Codigo_Registro)%%>', urlencode($combo_Codigo_Registro->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Tipo_Literatura)%%>', $combo_Tipo_Literatura->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Tipo_Literatura)%%>', $combo_Tipo_Literatura->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(Tipo_Documento)%%>', $combo_Tipo_Documento->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Tipo_Documento)%%>', $combo_Tipo_Documento->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Tipo_Documento)%%>', urlencode($combo_Tipo_Documento->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Estado_Catalogacion)%%>', $combo_id_Estado_Catalogacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Estado_Catalogacion)%%>', $combo_id_Estado_Catalogacion->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Estado_Catalogacion)%%>', urlencode($combo_id_Estado_Catalogacion->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Id_Autoridad)%%>', $combo_Id_Autoridad->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Id_Autoridad)%%>', $combo_Id_Autoridad->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Id_Autoridad)%%>', urlencode($combo_Id_Autoridad->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Id_Lugar)%%>', $combo_Id_Lugar->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Id_Lugar)%%>', $combo_Id_Lugar->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Id_Lugar)%%>', urlencode($combo_Id_Lugar->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Editorial)%%>', $combo_id_Editorial->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Editorial)%%>', $combo_id_Editorial->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Editorial)%%>', urlencode($combo_id_Editorial->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Materia_1)%%>', $combo_Materia_1->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Materia_1)%%>', $combo_Materia_1->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Materia_1)%%>', urlencode($combo_Materia_1->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Materia_2)%%>', $combo_Materia_2->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Materia_2)%%>', $combo_Materia_2->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Materia_2)%%>', urlencode($combo_Materia_2->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Materia_3)%%>', $combo_Materia_3->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Materia_3)%%>', $combo_Materia_3->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Materia_3)%%>', urlencode($combo_Materia_3->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(Fecha_Catalogacion)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_Fecha_Catalogacion->GetHTML(true) . '</div>' : 
			$combo_Fecha_Catalogacion->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Fecha_Catalogacion)%%>', $combo_Fecha_Catalogacion->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Codigo_Registro' => ['Registros', 'Codigo Registro'], 'Tipo_Documento' => ['Tipo_Documento', 'Tipo de Documento'], 'id_Estado_Catalogacion' => ['Estado_Catalogacion', 'Estado de Catalogacion'], 'Id_Autoridad' => ['Autoridades', 'Autor'], 'Id_Lugar' => ['Lugares', 'Lugar de Publicaci&#243;n'], 'id_Editorial' => ['Editoriales', 'Editorial'], 'Materia_1' => ['Materias', 'Materia 1'], 'Materia_2' => ['Materias', 'Materia 2'], 'Materia_3' => ['Materias', 'Materia 3'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Portada)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="Portada" id="Portada" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="102400000" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	if($AllowUpdate && $row['Portada'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(Portada)%%>', '<br><input type="checkbox" name="Portada_remove" id="Portada_remove" value="1"> <label for="Portada_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(Portada)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(Codigo_Registro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Item)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cod_Ejemplar)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Tipo_Literatura)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Tipo_Documento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Estado_Catalogacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Signatura_Topografica)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Id_Autoridad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Titulo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Responsabilidades)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Edicion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Id_Lugar)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Editorial)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Fecha_Publicacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Desc_Fisica)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Notas)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Materia_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Materia_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Materia_3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Ejemplares)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Fecha_Catalogacion)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$row['Portada'] = ($row['Portada'] != '' ? $row['Portada'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Portada)%%>', safe_html($urow['Portada']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Portada)%%>', html_attr($row['Portada']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Portada)%%>', urlencode($urow['Portada']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Codigo_Registro)%%>', safe_html($urow['Codigo_Registro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Codigo_Registro)%%>', html_attr($row['Codigo_Registro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo_Registro)%%>', urlencode($urow['Codigo_Registro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Item)%%>', safe_html($urow['Item']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Item)%%>', html_attr($row['Item']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Item)%%>', urlencode($urow['Item']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', safe_html($urow['Cod_Ejemplar']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', html_attr($row['Cod_Ejemplar']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode($urow['Cod_Ejemplar']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Tipo_Literatura)%%>', safe_html($urow['Tipo_Literatura']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Tipo_Literatura)%%>', html_attr($row['Tipo_Literatura']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tipo_Literatura)%%>', urlencode($urow['Tipo_Literatura']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Tipo_Documento)%%>', safe_html($urow['Tipo_Documento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Tipo_Documento)%%>', html_attr($row['Tipo_Documento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tipo_Documento)%%>', urlencode($urow['Tipo_Documento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Estado_Catalogacion)%%>', safe_html($urow['id_Estado_Catalogacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Estado_Catalogacion)%%>', html_attr($row['id_Estado_Catalogacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Estado_Catalogacion)%%>', urlencode($urow['id_Estado_Catalogacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Signatura_Topografica)%%>', safe_html($urow['Signatura_Topografica']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Signatura_Topografica)%%>', html_attr($row['Signatura_Topografica']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Signatura_Topografica)%%>', urlencode($urow['Signatura_Topografica']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Id_Autoridad)%%>', safe_html($urow['Id_Autoridad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Id_Autoridad)%%>', html_attr($row['Id_Autoridad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id_Autoridad)%%>', urlencode($urow['Id_Autoridad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Titulo)%%>', safe_html($urow['Titulo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Titulo)%%>', html_attr($row['Titulo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo)%%>', urlencode($urow['Titulo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Responsabilidades)%%>', safe_html($urow['Responsabilidades']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Responsabilidades)%%>', html_attr($row['Responsabilidades']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsabilidades)%%>', urlencode($urow['Responsabilidades']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Edicion)%%>', safe_html($urow['Edicion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Edicion)%%>', html_attr($row['Edicion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edicion)%%>', urlencode($urow['Edicion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Id_Lugar)%%>', safe_html($urow['Id_Lugar']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Id_Lugar)%%>', html_attr($row['Id_Lugar']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id_Lugar)%%>', urlencode($urow['Id_Lugar']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Editorial)%%>', safe_html($urow['id_Editorial']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Editorial)%%>', html_attr($row['id_Editorial']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Editorial)%%>', urlencode($urow['id_Editorial']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Fecha_Publicacion)%%>', safe_html($urow['Fecha_Publicacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Fecha_Publicacion)%%>', html_attr($row['Fecha_Publicacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Publicacion)%%>', urlencode($urow['Fecha_Publicacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Desc_Fisica)%%>', safe_html($urow['Desc_Fisica']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Desc_Fisica)%%>', html_attr($row['Desc_Fisica']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Desc_Fisica)%%>', urlencode($urow['Desc_Fisica']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Notas)%%>', safe_html($urow['Notas']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(Notas)%%>', safe_html($urow['Notas'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Notas)%%>', urlencode($urow['Notas']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Materia_1)%%>', safe_html($urow['Materia_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Materia_1)%%>', html_attr($row['Materia_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_1)%%>', urlencode($urow['Materia_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Materia_2)%%>', safe_html($urow['Materia_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Materia_2)%%>', html_attr($row['Materia_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_2)%%>', urlencode($urow['Materia_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Materia_3)%%>', safe_html($urow['Materia_3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Materia_3)%%>', html_attr($row['Materia_3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_3)%%>', urlencode($urow['Materia_3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Ejemplares)%%>', safe_html($urow['Ejemplares']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Ejemplares)%%>', html_attr($row['Ejemplares']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ejemplares)%%>', urlencode($urow['Ejemplares']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Catalogacion)%%>', app_datetime($row['Fecha_Catalogacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Catalogacion)%%>', urlencode(app_datetime($urow['Fecha_Catalogacion'])), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Portada)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(Codigo_Registro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Codigo_Registro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Item)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Item)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Tipo_Literatura)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tipo_Literatura)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Tipo_Documento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Tipo_Documento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Estado_Catalogacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Estado_Catalogacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Signatura_Topografica)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Signatura_Topografica)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Id_Autoridad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id_Autoridad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Titulo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Responsabilidades)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsabilidades)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Edicion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edicion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Id_Lugar)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id_Lugar)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Editorial)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Editorial)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Publicacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Publicacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Desc_Fisica)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Desc_Fisica)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Notas)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Notas)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Materia_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Materia_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Materia_3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Materia_3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Ejemplares)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Ejemplares)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Catalogacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Catalogacion)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tCodigo_Registro_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Catalogo_autofill.php?rnd1=$rnd1&mfk=Codigo_Registro&id=' + encodeURIComponent('".addslashes($row['Codigo_Registro'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Catalogo_autofill.php?rnd1=$rnd1&mfk=Codigo_Registro&id=' + encodeURIComponent(AppGini.current_Codigo_Registro{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Codigo_Registro$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#Codigo_Registro$rnd1').prop('disabled', false); " : "\$j('#Codigo_Registro$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Codigo_Registro_caption').length) \$j('#Codigo_Registro_caption').click(function() { Codigo_Registro_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Catalogo');
	if($selected_id) {
		$jdata = get_joined_record('Catalogo', $selected_id);
		if($jdata === false) $jdata = get_defaults('Catalogo');
		$rdata = $row;
	}
	$templateCode .= loadView('Catalogo-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Catalogo_dv
	if(function_exists('Catalogo_dv')) {
		$args = [];
		Catalogo_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}