<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('Catalogo');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'Codigo_Registro':
			if(!$id) {
				?>
				$j('#Cod_Barras<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `Registros`.`id` as 'id', `Registros`.`Codigo_de_Registro` as 'Codigo_de_Registro', `Registros`.`Codigo_Barras` as 'Codigo_Barras', IF(    CHAR_LENGTH(`Estado_Conservacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Conservacion1`.`Descripcion`), '') as 'id_Estado_Conservacion', IF(    CHAR_LENGTH(`Estado_Prestable1`.`Descripcion`), CONCAT_WS('',   `Estado_Prestable1`.`Descripcion`), '') as 'id_Estado_Prestable', if(`Registros`.`Fecha_Regsitro`,date_format(`Registros`.`Fecha_Regsitro`,'%m/%d/%Y'),'') as 'Fecha_Regsitro' FROM `Registros` LEFT JOIN `Estado_Conservacion` as Estado_Conservacion1 ON `Estado_Conservacion1`.`id`=`Registros`.`id_Estado_Conservacion` LEFT JOIN `Estado_Prestable` as Estado_Prestable1 ON `Estado_Prestable1`.`id`=`Registros`.`id_Estado_Prestable`  WHERE `Registros`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#Cod_Barras<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Codigo_Barras']))); ?>&nbsp;');
			<?php
			break;


	}

?>