<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Circulacion.php');
	include_once(__DIR__ . '/Circulacion_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Circulacion');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Circulacion';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Circulacion`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Apellidos`) || CHAR_LENGTH(`Usuarios1`.`Nombres`), CONCAT_WS('',   `Usuarios1`.`Apellidos`, ', ', `Usuarios1`.`Nombres`), '') /* Usuario */" => "id_Usuario",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Foto`), CONCAT_WS('',   `Usuarios1`.`Foto`), '') /* Foto Usuario */" => "Foto_Usuario",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Politica_de_Prestamos1`.`Duracion_Prestamo`) || CHAR_LENGTH(`Politica_de_Prestamos1`.`Lim_Doc_Presado`), CONCAT_WS('',   `Politica_de_Prestamos1`.`Duracion_Prestamo`, ' dias. L&#237;mite: ', `Politica_de_Prestamos1`.`Lim_Doc_Presado`), '') /* Politica de pretamo */" => "id_Politica_pretamo",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Registro */" => "id_Registro",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Titulo`), CONCAT_WS('',   `Catalogo1`.`Titulo`), '') /* Libro Prestado */" => "Libro_Prestado",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Portada`), CONCAT_WS('',   `Catalogo1`.`Portada`), '') /* Portada del Libro */" => "Portada_libro",
		"if(`Circulacion`.`Fecha_Prestamo`,date_format(`Circulacion`.`Fecha_Prestamo`,'%m/%d/%Y'),'')" => "Fecha_Prestamo",
		"if(`Circulacion`.`Fecha_Devolucion`,date_format(`Circulacion`.`Fecha_Devolucion`,'%m/%d/%Y'),'')" => "Fecha_Devolucion",
		"IF(    CHAR_LENGTH(`Estado_Prestamo1`.`Descripcion`), CONCAT_WS('',   `Estado_Prestamo1`.`Descripcion`), '') /* Estado de Prestamo */" => "id_Estado_prestamo",
		"`Circulacion`.`Cantidad`" => "Cantidad",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Ejemplares`), CONCAT_WS('',   `Catalogo1`.`Ejemplares`), '') /* Ejemplares Disponibles */" => "Ejemp_Disponibles",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Item */" => "Item",
		"IF(    CHAR_LENGTH(`Itemes1`.`Cod_Ejemplar`), CONCAT_WS('',   `Itemes1`.`Cod_Ejemplar`), '') /* Cod Ejemplar */" => "Cod_Ejemplar",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Circulacion`.`id`',
		2 => 2,
		3 => '`Usuarios1`.`Foto`',
		4 => '`Tipo_Usuario1`.`Descripcion`',
		5 => 5,
		6 => '`Tipo_Documento1`.`Descripcion`',
		7 => 7,
		8 => '`Catalogo1`.`Titulo`',
		9 => '`Catalogo1`.`Portada`',
		10 => '`Circulacion`.`Fecha_Prestamo`',
		11 => '`Circulacion`.`Fecha_Devolucion`',
		12 => '`Estado_Prestamo1`.`Descripcion`',
		13 => '`Circulacion`.`Cantidad`',
		14 => '`Catalogo1`.`Ejemplares`',
		15 => '`Catalogo1`.`Item`',
		16 => '`Itemes1`.`Cod_Ejemplar`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Circulacion`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Apellidos`) || CHAR_LENGTH(`Usuarios1`.`Nombres`), CONCAT_WS('',   `Usuarios1`.`Apellidos`, ', ', `Usuarios1`.`Nombres`), '') /* Usuario */" => "id_Usuario",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Foto`), CONCAT_WS('',   `Usuarios1`.`Foto`), '') /* Foto Usuario */" => "Foto_Usuario",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Politica_de_Prestamos1`.`Duracion_Prestamo`) || CHAR_LENGTH(`Politica_de_Prestamos1`.`Lim_Doc_Presado`), CONCAT_WS('',   `Politica_de_Prestamos1`.`Duracion_Prestamo`, ' dias. L&#237;mite: ', `Politica_de_Prestamos1`.`Lim_Doc_Presado`), '') /* Politica de pretamo */" => "id_Politica_pretamo",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Registro */" => "id_Registro",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Titulo`), CONCAT_WS('',   `Catalogo1`.`Titulo`), '') /* Libro Prestado */" => "Libro_Prestado",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Portada`), CONCAT_WS('',   `Catalogo1`.`Portada`), '') /* Portada del Libro */" => "Portada_libro",
		"if(`Circulacion`.`Fecha_Prestamo`,date_format(`Circulacion`.`Fecha_Prestamo`,'%m/%d/%Y'),'')" => "Fecha_Prestamo",
		"if(`Circulacion`.`Fecha_Devolucion`,date_format(`Circulacion`.`Fecha_Devolucion`,'%m/%d/%Y'),'')" => "Fecha_Devolucion",
		"IF(    CHAR_LENGTH(`Estado_Prestamo1`.`Descripcion`), CONCAT_WS('',   `Estado_Prestamo1`.`Descripcion`), '') /* Estado de Prestamo */" => "id_Estado_prestamo",
		"`Circulacion`.`Cantidad`" => "Cantidad",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Ejemplares`), CONCAT_WS('',   `Catalogo1`.`Ejemplares`), '') /* Ejemplares Disponibles */" => "Ejemp_Disponibles",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Item */" => "Item",
		"IF(    CHAR_LENGTH(`Itemes1`.`Cod_Ejemplar`), CONCAT_WS('',   `Itemes1`.`Cod_Ejemplar`), '') /* Cod Ejemplar */" => "Cod_Ejemplar",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Circulacion`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Apellidos`) || CHAR_LENGTH(`Usuarios1`.`Nombres`), CONCAT_WS('',   `Usuarios1`.`Apellidos`, ', ', `Usuarios1`.`Nombres`), '') /* Usuario */" => "Usuario",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Foto`), CONCAT_WS('',   `Usuarios1`.`Foto`), '') /* Foto Usuario */" => "Foto Usuario",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "Tipo de Usuario",
		"IF(    CHAR_LENGTH(`Politica_de_Prestamos1`.`Duracion_Prestamo`) || CHAR_LENGTH(`Politica_de_Prestamos1`.`Lim_Doc_Presado`), CONCAT_WS('',   `Politica_de_Prestamos1`.`Duracion_Prestamo`, ' dias. L&#237;mite: ', `Politica_de_Prestamos1`.`Lim_Doc_Presado`), '') /* Politica de pretamo */" => "Politica de pretamo",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "Tipo de documento",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Registro */" => "Registro",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Titulo`), CONCAT_WS('',   `Catalogo1`.`Titulo`), '') /* Libro Prestado */" => "Libro Prestado",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Portada`), CONCAT_WS('',   `Catalogo1`.`Portada`), '') /* Portada del Libro */" => "Portada del Libro",
		"`Circulacion`.`Fecha_Prestamo`" => "Fecha de Prestamo",
		"`Circulacion`.`Fecha_Devolucion`" => "Fecha de Devoluci&#243;n",
		"IF(    CHAR_LENGTH(`Estado_Prestamo1`.`Descripcion`), CONCAT_WS('',   `Estado_Prestamo1`.`Descripcion`), '') /* Estado de Prestamo */" => "Estado de Prestamo",
		"`Circulacion`.`Cantidad`" => "Cantidad",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Ejemplares`), CONCAT_WS('',   `Catalogo1`.`Ejemplares`), '') /* Ejemplares Disponibles */" => "Ejemplares Disponibles",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Item */" => "Item",
		"IF(    CHAR_LENGTH(`Itemes1`.`Cod_Ejemplar`), CONCAT_WS('',   `Itemes1`.`Cod_Ejemplar`), '') /* Cod Ejemplar */" => "Cod Ejemplar",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Circulacion`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Apellidos`) || CHAR_LENGTH(`Usuarios1`.`Nombres`), CONCAT_WS('',   `Usuarios1`.`Apellidos`, ', ', `Usuarios1`.`Nombres`), '') /* Usuario */" => "id_Usuario",
		"IF(    CHAR_LENGTH(`Usuarios1`.`Foto`), CONCAT_WS('',   `Usuarios1`.`Foto`), '') /* Foto Usuario */" => "Foto_Usuario",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Politica_de_Prestamos1`.`Duracion_Prestamo`) || CHAR_LENGTH(`Politica_de_Prestamos1`.`Lim_Doc_Presado`), CONCAT_WS('',   `Politica_de_Prestamos1`.`Duracion_Prestamo`, ' dias. L&#237;mite: ', `Politica_de_Prestamos1`.`Lim_Doc_Presado`), '') /* Politica de pretamo */" => "id_Politica_pretamo",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"IF(    CHAR_LENGTH(`Registros1`.`Codigo_de_Registro`), CONCAT_WS('',   `Registros1`.`Codigo_de_Registro`), '') /* Registro */" => "id_Registro",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Titulo`), CONCAT_WS('',   `Catalogo1`.`Titulo`), '') /* Libro Prestado */" => "Libro_Prestado",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Portada`), CONCAT_WS('',   `Catalogo1`.`Portada`), '') /* Portada del Libro */" => "Portada_libro",
		"if(`Circulacion`.`Fecha_Prestamo`,date_format(`Circulacion`.`Fecha_Prestamo`,'%m/%d/%Y'),'')" => "Fecha_Prestamo",
		"if(`Circulacion`.`Fecha_Devolucion`,date_format(`Circulacion`.`Fecha_Devolucion`,'%m/%d/%Y'),'')" => "Fecha_Devolucion",
		"IF(    CHAR_LENGTH(`Estado_Prestamo1`.`Descripcion`), CONCAT_WS('',   `Estado_Prestamo1`.`Descripcion`), '') /* Estado de Prestamo */" => "id_Estado_prestamo",
		"`Circulacion`.`Cantidad`" => "Cantidad",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Ejemplares`), CONCAT_WS('',   `Catalogo1`.`Ejemplares`), '') /* Ejemplares Disponibles */" => "Ejemp_Disponibles",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Item */" => "Item",
		"IF(    CHAR_LENGTH(`Itemes1`.`Cod_Ejemplar`), CONCAT_WS('',   `Itemes1`.`Cod_Ejemplar`), '') /* Cod Ejemplar */" => "Cod_Ejemplar",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_Usuario' => 'Usuario', 'id_Tipo_usuario' => 'Tipo de Usuario', 'id_Politica_pretamo' => 'Politica de pretamo', 'id_Tipo_documento' => 'Tipo de documento', 'Libro_Prestado' => 'Libro Prestado', 'id_Estado_prestamo' => 'Estado de Prestamo', 'Cod_Ejemplar' => 'Cod Ejemplar', ];

	$x->QueryFrom = "`Circulacion` LEFT JOIN `Usuarios` as Usuarios1 ON `Usuarios1`.`id`=`Circulacion`.`id_Usuario` LEFT JOIN `Tipo_Usuario` as Tipo_Usuario1 ON `Tipo_Usuario1`.`id`=`Circulacion`.`id_Tipo_usuario` LEFT JOIN `Politica_de_Prestamos` as Politica_de_Prestamos1 ON `Politica_de_Prestamos1`.`id`=`Circulacion`.`id_Politica_pretamo` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Circulacion`.`id_Tipo_documento` LEFT JOIN `Catalogo` as Catalogo1 ON `Catalogo1`.`id`=`Circulacion`.`Libro_Prestado` LEFT JOIN `Estado_Prestamo` as Estado_Prestamo1 ON `Estado_Prestamo1`.`id`=`Circulacion`.`id_Estado_prestamo` LEFT JOIN `Itemes` as Itemes1 ON `Itemes1`.`id`=`Circulacion`.`Cod_Ejemplar` LEFT JOIN `Registros` as Registros1 ON `Registros1`.`id`=`Catalogo1`.`Codigo_Registro` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Circulacion_view.php';
	$x->TableTitle = 'Circulacion';
	$x->TableIcon = 'resources/table_icons/arrow_refresh.png';
	$x->PrimaryKey = '`Circulacion`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Usuario', 'Foto Usuario', 'Tipo de Usuario', 'Politica de pretamo', 'Tipo de documento', 'Registro', 'Libro Prestado', 'Portada del Libro', 'Fecha de Prestamo', 'Fecha de Devoluci&#243;n', 'Estado de Prestamo', 'Cantidad', 'Ejemplares Disponibles', 'Item', 'Cod Ejemplar', ];
	$x->ColFieldName = ['id_Usuario', 'Foto_Usuario', 'id_Tipo_usuario', 'id_Politica_pretamo', 'id_Tipo_documento', 'id_Registro', 'Libro_Prestado', 'Portada_libro', 'Fecha_Prestamo', 'Fecha_Devolucion', 'id_Estado_prestamo', 'Cantidad', 'Ejemp_Disponibles', 'Item', 'Cod_Ejemplar', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Circulacion_templateTV.html';
	$x->SelectedTemplate = 'templates/Circulacion_templateTVS.html';
	$x->TemplateDV = 'templates/Circulacion_templateDV.html';
	$x->TemplateDVP = 'templates/Circulacion_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Circulacion_init
	$render = true;
	if(function_exists('Circulacion_init')) {
		$args = [];
		$render = Circulacion_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Circulacion_header
	$headerCode = '';
	if(function_exists('Circulacion_header')) {
		$args = [];
		$headerCode = Circulacion_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Circulacion_footer
	$footerCode = '';
	if(function_exists('Circulacion_footer')) {
		$args = [];
		$footerCode = Circulacion_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
