<?php

// Data functions (insert, update, delete, form) for table Circulacion

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function Circulacion_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Circulacion');
	if(!$arrPerm['insert']) return false;

	$data = [
		'id_Usuario' => Request::lookup('id_Usuario', ''),
		'Foto_Usuario' => Request::lookup('id_Usuario'),
		'id_Tipo_usuario' => Request::lookup('id_Tipo_usuario', ''),
		'id_Politica_pretamo' => Request::lookup('id_Politica_pretamo', ''),
		'id_Tipo_documento' => Request::lookup('id_Tipo_documento', ''),
		'id_Registro' => Request::lookup('Libro_Prestado'),
		'Libro_Prestado' => Request::lookup('Libro_Prestado', ''),
		'Portada_libro' => Request::lookup('Libro_Prestado'),
		'Fecha_Prestamo' => Request::dateComponents('Fecha_Prestamo', ''),
		'Fecha_Devolucion' => Request::dateComponents('Fecha_Devolucion', ''),
		'id_Estado_prestamo' => Request::lookup('id_Estado_prestamo', ''),
		'Cantidad' => Request::val('Cantidad', ''),
		'Ejemp_Disponibles' => Request::lookup('Libro_Prestado'),
		'Item' => Request::lookup('Libro_Prestado'),
		'Cod_Ejemplar' => Request::lookup('Cod_Ejemplar', ''),
	];


	// hook: Circulacion_before_insert
	if(function_exists('Circulacion_before_insert')) {
		$args = [];
		if(!Circulacion_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Circulacion', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Circulacion', $recID, calculated_fields()['Circulacion']);

	// hook: Circulacion_after_insert
	if(function_exists('Circulacion_after_insert')) {
		$res = sql("SELECT * FROM `Circulacion` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Circulacion_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Circulacion', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Circulacion_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Circulacion_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Circulacion_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Circulacion', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Circulacion_before_delete
	if(function_exists('Circulacion_before_delete')) {
		$args = [];
		if(!Circulacion_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Circulacion` WHERE `id`='{$selected_id}'", $eo);

	// hook: Circulacion_after_delete
	if(function_exists('Circulacion_after_delete')) {
		$args = [];
		Circulacion_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Circulacion' AND `pkValue`='{$selected_id}'", $eo);
}

function Circulacion_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Circulacion', $selected_id, 'edit')) return false;

	$data = [
		'id_Usuario' => Request::lookup('id_Usuario', ''),
		'Foto_Usuario' => Request::lookup('id_Usuario'),
		'id_Tipo_usuario' => Request::lookup('id_Tipo_usuario', ''),
		'id_Politica_pretamo' => Request::lookup('id_Politica_pretamo', ''),
		'id_Tipo_documento' => Request::lookup('id_Tipo_documento', ''),
		'id_Registro' => Request::lookup('Libro_Prestado'),
		'Libro_Prestado' => Request::lookup('Libro_Prestado', ''),
		'Portada_libro' => Request::lookup('Libro_Prestado'),
		'Fecha_Prestamo' => Request::dateComponents('Fecha_Prestamo', ''),
		'Fecha_Devolucion' => Request::dateComponents('Fecha_Devolucion', ''),
		'id_Estado_prestamo' => Request::lookup('id_Estado_prestamo', ''),
		'Cantidad' => Request::val('Cantidad', ''),
		'Ejemp_Disponibles' => Request::lookup('Libro_Prestado'),
		'Item' => Request::lookup('Libro_Prestado'),
		'Cod_Ejemplar' => Request::lookup('Cod_Ejemplar', ''),
	];

	// get existing values
	$old_data = getRecord('Circulacion', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Circulacion_before_update
	if(function_exists('Circulacion_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Circulacion_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Circulacion', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Circulacion_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Circulacion', $data['selectedID'], calculated_fields()['Circulacion']);

	// hook: Circulacion_after_update
	if(function_exists('Circulacion_after_update')) {
		$res = sql("SELECT * FROM `Circulacion` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Circulacion_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Circulacion' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Circulacion_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Circulacion');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_id_Usuario = Request::val('filterer_id_Usuario');
	$filterer_id_Tipo_usuario = Request::val('filterer_id_Tipo_usuario');
	$filterer_id_Politica_pretamo = Request::val('filterer_id_Politica_pretamo');
	$filterer_id_Tipo_documento = Request::val('filterer_id_Tipo_documento');
	$filterer_Libro_Prestado = Request::val('filterer_Libro_Prestado');
	$filterer_id_Estado_prestamo = Request::val('filterer_id_Estado_prestamo');
	$filterer_Cod_Ejemplar = Request::val('filterer_Cod_Ejemplar');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: id_Usuario
	$combo_id_Usuario = new DataCombo;
	// combobox: id_Tipo_usuario
	$combo_id_Tipo_usuario = new DataCombo;
	// combobox: id_Politica_pretamo
	$combo_id_Politica_pretamo = new DataCombo;
	// combobox: id_Tipo_documento
	$combo_id_Tipo_documento = new DataCombo;
	// combobox: Libro_Prestado
	$combo_Libro_Prestado = new DataCombo;
	// combobox: Fecha_Prestamo
	$combo_Fecha_Prestamo = new DateCombo;
	$combo_Fecha_Prestamo->DateFormat = "mdy";
	$combo_Fecha_Prestamo->MinYear = defined('Circulacion.Fecha_Prestamo.MinYear') ? constant('Circulacion.Fecha_Prestamo.MinYear') : 1900;
	$combo_Fecha_Prestamo->MaxYear = defined('Circulacion.Fecha_Prestamo.MaxYear') ? constant('Circulacion.Fecha_Prestamo.MaxYear') : 2100;
	$combo_Fecha_Prestamo->DefaultDate = parseMySQLDate('', '');
	$combo_Fecha_Prestamo->MonthNames = $Translation['month names'];
	$combo_Fecha_Prestamo->NamePrefix = 'Fecha_Prestamo';
	// combobox: Fecha_Devolucion
	$combo_Fecha_Devolucion = new DateCombo;
	$combo_Fecha_Devolucion->DateFormat = "mdy";
	$combo_Fecha_Devolucion->MinYear = defined('Circulacion.Fecha_Devolucion.MinYear') ? constant('Circulacion.Fecha_Devolucion.MinYear') : 1900;
	$combo_Fecha_Devolucion->MaxYear = defined('Circulacion.Fecha_Devolucion.MaxYear') ? constant('Circulacion.Fecha_Devolucion.MaxYear') : 2100;
	$combo_Fecha_Devolucion->DefaultDate = parseMySQLDate('', '');
	$combo_Fecha_Devolucion->MonthNames = $Translation['month names'];
	$combo_Fecha_Devolucion->NamePrefix = 'Fecha_Devolucion';
	// combobox: id_Estado_prestamo
	$combo_id_Estado_prestamo = new DataCombo;
	// combobox: Cod_Ejemplar
	$combo_Cod_Ejemplar = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Circulacion' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Circulacion' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Circulacion` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Circulacion_view.php', false);
		}
		$combo_id_Usuario->SelectedData = $row['id_Usuario'];
		$combo_id_Tipo_usuario->SelectedData = $row['id_Tipo_usuario'];
		$combo_id_Politica_pretamo->SelectedData = $row['id_Politica_pretamo'];
		$combo_id_Tipo_documento->SelectedData = $row['id_Tipo_documento'];
		$combo_Libro_Prestado->SelectedData = $row['Libro_Prestado'];
		$combo_Fecha_Prestamo->DefaultDate = $row['Fecha_Prestamo'];
		$combo_Fecha_Devolucion->DefaultDate = $row['Fecha_Devolucion'];
		$combo_id_Estado_prestamo->SelectedData = $row['id_Estado_prestamo'];
		$combo_Cod_Ejemplar->SelectedData = $row['Cod_Ejemplar'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_id_Usuario->SelectedData = $filterer_id_Usuario;
		$combo_id_Tipo_usuario->SelectedData = $filterer_id_Tipo_usuario;
		$combo_id_Politica_pretamo->SelectedData = $filterer_id_Politica_pretamo;
		$combo_id_Tipo_documento->SelectedData = $filterer_id_Tipo_documento;
		$combo_Libro_Prestado->SelectedData = $filterer_Libro_Prestado;
		$combo_id_Estado_prestamo->SelectedData = $filterer_id_Estado_prestamo;
		$combo_Cod_Ejemplar->SelectedData = $filterer_Cod_Ejemplar;
	}
	$combo_id_Usuario->HTML = '<span id="id_Usuario-container' . $rnd1 . '"></span><input type="hidden" name="id_Usuario" id="id_Usuario' . $rnd1 . '" value="' . html_attr($combo_id_Usuario->SelectedData) . '">';
	$combo_id_Usuario->MatchText = '<span id="id_Usuario-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Usuario" id="id_Usuario' . $rnd1 . '" value="' . html_attr($combo_id_Usuario->SelectedData) . '">';
	$combo_id_Tipo_usuario->HTML = '<span id="id_Tipo_usuario-container' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_usuario" id="id_Tipo_usuario' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_usuario->SelectedData) . '">';
	$combo_id_Tipo_usuario->MatchText = '<span id="id_Tipo_usuario-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_usuario" id="id_Tipo_usuario' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_usuario->SelectedData) . '">';
	$combo_id_Politica_pretamo->HTML = '<span id="id_Politica_pretamo-container' . $rnd1 . '"></span><input type="hidden" name="id_Politica_pretamo" id="id_Politica_pretamo' . $rnd1 . '" value="' . html_attr($combo_id_Politica_pretamo->SelectedData) . '">';
	$combo_id_Politica_pretamo->MatchText = '<span id="id_Politica_pretamo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Politica_pretamo" id="id_Politica_pretamo' . $rnd1 . '" value="' . html_attr($combo_id_Politica_pretamo->SelectedData) . '">';
	$combo_id_Tipo_documento->HTML = '<span id="id_Tipo_documento-container' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_documento" id="id_Tipo_documento' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_documento->SelectedData) . '">';
	$combo_id_Tipo_documento->MatchText = '<span id="id_Tipo_documento-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_documento" id="id_Tipo_documento' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_documento->SelectedData) . '">';
	$combo_Libro_Prestado->HTML = '<span id="Libro_Prestado-container' . $rnd1 . '"></span><input type="hidden" name="Libro_Prestado" id="Libro_Prestado' . $rnd1 . '" value="' . html_attr($combo_Libro_Prestado->SelectedData) . '">';
	$combo_Libro_Prestado->MatchText = '<span id="Libro_Prestado-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Libro_Prestado" id="Libro_Prestado' . $rnd1 . '" value="' . html_attr($combo_Libro_Prestado->SelectedData) . '">';
	$combo_id_Estado_prestamo->HTML = '<span id="id_Estado_prestamo-container' . $rnd1 . '"></span><input type="hidden" name="id_Estado_prestamo" id="id_Estado_prestamo' . $rnd1 . '" value="' . html_attr($combo_id_Estado_prestamo->SelectedData) . '">';
	$combo_id_Estado_prestamo->MatchText = '<span id="id_Estado_prestamo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Estado_prestamo" id="id_Estado_prestamo' . $rnd1 . '" value="' . html_attr($combo_id_Estado_prestamo->SelectedData) . '">';
	$combo_Cod_Ejemplar->HTML = '<span id="Cod_Ejemplar-container' . $rnd1 . '"></span><input type="hidden" name="Cod_Ejemplar" id="Cod_Ejemplar' . $rnd1 . '" value="' . html_attr($combo_Cod_Ejemplar->SelectedData) . '">';
	$combo_Cod_Ejemplar->MatchText = '<span id="Cod_Ejemplar-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Cod_Ejemplar" id="Cod_Ejemplar' . $rnd1 . '" value="' . html_attr($combo_Cod_Ejemplar->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_id_Usuario__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Usuario'] : htmlspecialchars($filterer_id_Usuario, ENT_QUOTES)); ?>"};
		AppGini.current_id_Tipo_usuario__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Tipo_usuario'] : htmlspecialchars($filterer_id_Tipo_usuario, ENT_QUOTES)); ?>"};
		AppGini.current_id_Politica_pretamo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Politica_pretamo'] : htmlspecialchars($filterer_id_Politica_pretamo, ENT_QUOTES)); ?>"};
		AppGini.current_id_Tipo_documento__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Tipo_documento'] : htmlspecialchars($filterer_id_Tipo_documento, ENT_QUOTES)); ?>"};
		AppGini.current_Libro_Prestado__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Libro_Prestado'] : htmlspecialchars($filterer_Libro_Prestado, ENT_QUOTES)); ?>"};
		AppGini.current_id_Estado_prestamo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Estado_prestamo'] : htmlspecialchars($filterer_id_Estado_prestamo, ENT_QUOTES)); ?>"};
		AppGini.current_Cod_Ejemplar__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Cod_Ejemplar'] : htmlspecialchars($filterer_Cod_Ejemplar, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(id_Usuario_reload__RAND__) == 'function') id_Usuario_reload__RAND__();
				if(typeof(id_Tipo_usuario_reload__RAND__) == 'function') id_Tipo_usuario_reload__RAND__();
				if(typeof(id_Politica_pretamo_reload__RAND__) == 'function') id_Politica_pretamo_reload__RAND__();
				if(typeof(id_Tipo_documento_reload__RAND__) == 'function') id_Tipo_documento_reload__RAND__();
				if(typeof(Libro_Prestado_reload__RAND__) == 'function') Libro_Prestado_reload__RAND__();
				if(typeof(id_Estado_prestamo_reload__RAND__) == 'function') id_Estado_prestamo_reload__RAND__();
				if(typeof(Cod_Ejemplar_reload__RAND__) == 'function') Cod_Ejemplar_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function id_Usuario_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Usuario-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Usuario__RAND__.value, t: 'Circulacion', f: 'id_Usuario' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Usuario"]').val(resp.results[0].id);
							$j('[id=id_Usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Usuario-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Usuarios_view_parent]').hide(); } else { $j('.btn[id=Usuarios_view_parent]').show(); }


							if(typeof(id_Usuario_update_autofills__RAND__) == 'function') id_Usuario_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'id_Usuario' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Usuario__RAND__.value = e.added.id;
				AppGini.current_id_Usuario__RAND__.text = e.added.text;
				$j('[name="id_Usuario"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Usuarios_view_parent]').hide(); } else { $j('.btn[id=Usuarios_view_parent]').show(); }


				if(typeof(id_Usuario_update_autofills__RAND__) == 'function') id_Usuario_update_autofills__RAND__();
			});

			if(!$j("#id_Usuario-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Usuario__RAND__.value, t: 'Circulacion', f: 'id_Usuario' },
					success: function(resp) {
						$j('[name="id_Usuario"]').val(resp.results[0].id);
						$j('[id=id_Usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Usuario-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Usuarios_view_parent]').hide(); } else { $j('.btn[id=Usuarios_view_parent]').show(); }

						if(typeof(id_Usuario_update_autofills__RAND__) == 'function') id_Usuario_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Usuario__RAND__.value, t: 'Circulacion', f: 'id_Usuario' },
				success: function(resp) {
					$j('[id=id_Usuario-container__RAND__], [id=id_Usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Usuario-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Usuarios_view_parent]').hide(); } else { $j('.btn[id=Usuarios_view_parent]').show(); }

					if(typeof(id_Usuario_update_autofills__RAND__) == 'function') id_Usuario_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Tipo_usuario_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Tipo_usuario-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Circulacion', f: 'id_Tipo_usuario' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Tipo_usuario"]').val(resp.results[0].id);
							$j('[id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }


							if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'id_Tipo_usuario' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Tipo_usuario__RAND__.value = e.added.id;
				AppGini.current_id_Tipo_usuario__RAND__.text = e.added.text;
				$j('[name="id_Tipo_usuario"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }


				if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
			});

			if(!$j("#id_Tipo_usuario-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Circulacion', f: 'id_Tipo_usuario' },
					success: function(resp) {
						$j('[name="id_Tipo_usuario"]').val(resp.results[0].id);
						$j('[id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }

						if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Circulacion', f: 'id_Tipo_usuario' },
				success: function(resp) {
					$j('[id=id_Tipo_usuario-container__RAND__], [id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }

					if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Politica_pretamo_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Politica_pretamo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Politica_pretamo__RAND__.value, t: 'Circulacion', f: 'id_Politica_pretamo' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Politica_pretamo"]').val(resp.results[0].id);
							$j('[id=id_Politica_pretamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Politica_pretamo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Politica_de_Prestamos_view_parent]').hide(); } else { $j('.btn[id=Politica_de_Prestamos_view_parent]').show(); }


							if(typeof(id_Politica_pretamo_update_autofills__RAND__) == 'function') id_Politica_pretamo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'id_Politica_pretamo' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Politica_pretamo__RAND__.value = e.added.id;
				AppGini.current_id_Politica_pretamo__RAND__.text = e.added.text;
				$j('[name="id_Politica_pretamo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Politica_de_Prestamos_view_parent]').hide(); } else { $j('.btn[id=Politica_de_Prestamos_view_parent]').show(); }


				if(typeof(id_Politica_pretamo_update_autofills__RAND__) == 'function') id_Politica_pretamo_update_autofills__RAND__();
			});

			if(!$j("#id_Politica_pretamo-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Politica_pretamo__RAND__.value, t: 'Circulacion', f: 'id_Politica_pretamo' },
					success: function(resp) {
						$j('[name="id_Politica_pretamo"]').val(resp.results[0].id);
						$j('[id=id_Politica_pretamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Politica_pretamo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Politica_de_Prestamos_view_parent]').hide(); } else { $j('.btn[id=Politica_de_Prestamos_view_parent]').show(); }

						if(typeof(id_Politica_pretamo_update_autofills__RAND__) == 'function') id_Politica_pretamo_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Politica_pretamo__RAND__.value, t: 'Circulacion', f: 'id_Politica_pretamo' },
				success: function(resp) {
					$j('[id=id_Politica_pretamo-container__RAND__], [id=id_Politica_pretamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Politica_pretamo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Politica_de_Prestamos_view_parent]').hide(); } else { $j('.btn[id=Politica_de_Prestamos_view_parent]').show(); }

					if(typeof(id_Politica_pretamo_update_autofills__RAND__) == 'function') id_Politica_pretamo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Tipo_documento_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Tipo_documento-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Circulacion', f: 'id_Tipo_documento' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Tipo_documento"]').val(resp.results[0].id);
							$j('[id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


							if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'id_Tipo_documento' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Tipo_documento__RAND__.value = e.added.id;
				AppGini.current_id_Tipo_documento__RAND__.text = e.added.text;
				$j('[name="id_Tipo_documento"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


				if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
			});

			if(!$j("#id_Tipo_documento-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Circulacion', f: 'id_Tipo_documento' },
					success: function(resp) {
						$j('[name="id_Tipo_documento"]').val(resp.results[0].id);
						$j('[id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

						if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Circulacion', f: 'id_Tipo_documento' },
				success: function(resp) {
					$j('[id=id_Tipo_documento-container__RAND__], [id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

					if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Libro_Prestado_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Libro_Prestado-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Libro_Prestado__RAND__.value, t: 'Circulacion', f: 'Libro_Prestado' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Libro_Prestado"]').val(resp.results[0].id);
							$j('[id=Libro_Prestado-container-readonly__RAND__]').html('<span class="match-text" id="Libro_Prestado-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }


							if(typeof(Libro_Prestado_update_autofills__RAND__) == 'function') Libro_Prestado_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'Libro_Prestado' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Libro_Prestado__RAND__.value = e.added.id;
				AppGini.current_Libro_Prestado__RAND__.text = e.added.text;
				$j('[name="Libro_Prestado"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }


				if(typeof(Libro_Prestado_update_autofills__RAND__) == 'function') Libro_Prestado_update_autofills__RAND__();
			});

			if(!$j("#Libro_Prestado-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Libro_Prestado__RAND__.value, t: 'Circulacion', f: 'Libro_Prestado' },
					success: function(resp) {
						$j('[name="Libro_Prestado"]').val(resp.results[0].id);
						$j('[id=Libro_Prestado-container-readonly__RAND__]').html('<span class="match-text" id="Libro_Prestado-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }

						if(typeof(Libro_Prestado_update_autofills__RAND__) == 'function') Libro_Prestado_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Libro_Prestado__RAND__.value, t: 'Circulacion', f: 'Libro_Prestado' },
				success: function(resp) {
					$j('[id=Libro_Prestado-container__RAND__], [id=Libro_Prestado-container-readonly__RAND__]').html('<span class="match-text" id="Libro_Prestado-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }

					if(typeof(Libro_Prestado_update_autofills__RAND__) == 'function') Libro_Prestado_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Estado_prestamo_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Estado_prestamo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Estado_prestamo__RAND__.value, t: 'Circulacion', f: 'id_Estado_prestamo' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Estado_prestamo"]').val(resp.results[0].id);
							$j('[id=id_Estado_prestamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_prestamo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Prestamo_view_parent]').hide(); } else { $j('.btn[id=Estado_Prestamo_view_parent]').show(); }


							if(typeof(id_Estado_prestamo_update_autofills__RAND__) == 'function') id_Estado_prestamo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'id_Estado_prestamo' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Estado_prestamo__RAND__.value = e.added.id;
				AppGini.current_id_Estado_prestamo__RAND__.text = e.added.text;
				$j('[name="id_Estado_prestamo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Prestamo_view_parent]').hide(); } else { $j('.btn[id=Estado_Prestamo_view_parent]').show(); }


				if(typeof(id_Estado_prestamo_update_autofills__RAND__) == 'function') id_Estado_prestamo_update_autofills__RAND__();
			});

			if(!$j("#id_Estado_prestamo-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Estado_prestamo__RAND__.value, t: 'Circulacion', f: 'id_Estado_prestamo' },
					success: function(resp) {
						$j('[name="id_Estado_prestamo"]').val(resp.results[0].id);
						$j('[id=id_Estado_prestamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_prestamo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Prestamo_view_parent]').hide(); } else { $j('.btn[id=Estado_Prestamo_view_parent]').show(); }

						if(typeof(id_Estado_prestamo_update_autofills__RAND__) == 'function') id_Estado_prestamo_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Estado_prestamo__RAND__.value, t: 'Circulacion', f: 'id_Estado_prestamo' },
				success: function(resp) {
					$j('[id=id_Estado_prestamo-container__RAND__], [id=id_Estado_prestamo-container-readonly__RAND__]').html('<span class="match-text" id="id_Estado_prestamo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Prestamo_view_parent]').hide(); } else { $j('.btn[id=Estado_Prestamo_view_parent]').show(); }

					if(typeof(id_Estado_prestamo_update_autofills__RAND__) == 'function') id_Estado_prestamo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Cod_Ejemplar_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Cod_Ejemplar-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Cod_Ejemplar__RAND__.value, t: 'Circulacion', f: 'Cod_Ejemplar' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Cod_Ejemplar"]').val(resp.results[0].id);
							$j('[id=Cod_Ejemplar-container-readonly__RAND__]').html('<span class="match-text" id="Cod_Ejemplar-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Itemes_view_parent]').hide(); } else { $j('.btn[id=Itemes_view_parent]').show(); }


							if(typeof(Cod_Ejemplar_update_autofills__RAND__) == 'function') Cod_Ejemplar_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Circulacion', f: 'Cod_Ejemplar' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Cod_Ejemplar__RAND__.value = e.added.id;
				AppGini.current_Cod_Ejemplar__RAND__.text = e.added.text;
				$j('[name="Cod_Ejemplar"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Itemes_view_parent]').hide(); } else { $j('.btn[id=Itemes_view_parent]').show(); }


				if(typeof(Cod_Ejemplar_update_autofills__RAND__) == 'function') Cod_Ejemplar_update_autofills__RAND__();
			});

			if(!$j("#Cod_Ejemplar-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Cod_Ejemplar__RAND__.value, t: 'Circulacion', f: 'Cod_Ejemplar' },
					success: function(resp) {
						$j('[name="Cod_Ejemplar"]').val(resp.results[0].id);
						$j('[id=Cod_Ejemplar-container-readonly__RAND__]').html('<span class="match-text" id="Cod_Ejemplar-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Itemes_view_parent]').hide(); } else { $j('.btn[id=Itemes_view_parent]').show(); }

						if(typeof(Cod_Ejemplar_update_autofills__RAND__) == 'function') Cod_Ejemplar_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Cod_Ejemplar__RAND__.value, t: 'Circulacion', f: 'Cod_Ejemplar' },
				success: function(resp) {
					$j('[id=Cod_Ejemplar-container__RAND__], [id=Cod_Ejemplar-container-readonly__RAND__]').html('<span class="match-text" id="Cod_Ejemplar-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Itemes_view_parent]').hide(); } else { $j('.btn[id=Itemes_view_parent]').show(); }

					if(typeof(Cod_Ejemplar_update_autofills__RAND__) == 'function') Cod_Ejemplar_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Circulacion_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Circulacion_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Circulacion details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Circulacion_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Circulacion_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Circulacion_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#id_Usuario').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Usuario_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_usuario').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_usuario_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Politica_pretamo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Politica_pretamo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_documento').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_documento_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Libro_Prestado').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Libro_Prestado_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Fecha_Prestamo').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Fecha_PrestamoDay, #Fecha_PrestamoMonth, #Fecha_PrestamoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Fecha_Devolucion').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Fecha_DevolucionDay, #Fecha_DevolucionMonth, #Fecha_DevolucionYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Estado_prestamo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Estado_prestamo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Cantidad').replaceWith('<div class=\"form-control-static\" id=\"Cantidad\">' + (jQuery('#Cantidad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Cod_Ejemplar').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Cod_Ejemplar_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(id_Usuario)%%>', $combo_id_Usuario->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Usuario)%%>', $combo_id_Usuario->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Usuario)%%>', urlencode($combo_id_Usuario->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Tipo_usuario)%%>', $combo_id_Tipo_usuario->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Tipo_usuario)%%>', $combo_id_Tipo_usuario->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Tipo_usuario)%%>', urlencode($combo_id_Tipo_usuario->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Politica_pretamo)%%>', $combo_id_Politica_pretamo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Politica_pretamo)%%>', $combo_id_Politica_pretamo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Politica_pretamo)%%>', urlencode($combo_id_Politica_pretamo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Tipo_documento)%%>', $combo_id_Tipo_documento->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Tipo_documento)%%>', $combo_id_Tipo_documento->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Tipo_documento)%%>', urlencode($combo_id_Tipo_documento->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Libro_Prestado)%%>', $combo_Libro_Prestado->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Libro_Prestado)%%>', $combo_Libro_Prestado->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Libro_Prestado)%%>', urlencode($combo_Libro_Prestado->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(Fecha_Prestamo)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_Fecha_Prestamo->GetHTML(true) . '</div>' : 
			$combo_Fecha_Prestamo->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Fecha_Prestamo)%%>', $combo_Fecha_Prestamo->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(Fecha_Devolucion)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_Fecha_Devolucion->GetHTML(true) . '</div>' : 
			$combo_Fecha_Devolucion->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Fecha_Devolucion)%%>', $combo_Fecha_Devolucion->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Estado_prestamo)%%>', $combo_id_Estado_prestamo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Estado_prestamo)%%>', $combo_id_Estado_prestamo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Estado_prestamo)%%>', urlencode($combo_id_Estado_prestamo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Cod_Ejemplar)%%>', $combo_Cod_Ejemplar->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Cod_Ejemplar)%%>', $combo_Cod_Ejemplar->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Cod_Ejemplar)%%>', urlencode($combo_Cod_Ejemplar->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['id_Usuario' => ['Usuarios', 'Usuario'], 'id_Tipo_usuario' => ['Tipo_Usuario', 'Tipo de Usuario'], 'id_Politica_pretamo' => ['Politica_de_Prestamos', 'Politica de pretamo'], 'id_Tipo_documento' => ['Tipo_Documento', 'Tipo de documento'], 'Libro_Prestado' => ['Catalogo', 'Libro Prestado'], 'id_Estado_prestamo' => ['Estado_Prestamo', 'Estado de Prestamo'], 'Cod_Ejemplar' => ['Itemes', 'Cod Ejemplar'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Usuario)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Tipo_usuario)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Politica_pretamo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Tipo_documento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Libro_Prestado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Fecha_Prestamo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Fecha_Devolucion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Estado_prestamo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cantidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cod_Ejemplar)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Usuario)%%>', safe_html($urow['id_Usuario']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Usuario)%%>', html_attr($row['id_Usuario']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Usuario)%%>', urlencode($urow['id_Usuario']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', safe_html($urow['id_Tipo_usuario']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', html_attr($row['id_Tipo_usuario']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_usuario)%%>', urlencode($urow['id_Tipo_usuario']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Politica_pretamo)%%>', safe_html($urow['id_Politica_pretamo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Politica_pretamo)%%>', html_attr($row['id_Politica_pretamo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Politica_pretamo)%%>', urlencode($urow['id_Politica_pretamo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', safe_html($urow['id_Tipo_documento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', html_attr($row['id_Tipo_documento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_documento)%%>', urlencode($urow['id_Tipo_documento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Libro_Prestado)%%>', safe_html($urow['Libro_Prestado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Libro_Prestado)%%>', html_attr($row['Libro_Prestado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Libro_Prestado)%%>', urlencode($urow['Libro_Prestado']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Prestamo)%%>', app_datetime($row['Fecha_Prestamo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Prestamo)%%>', urlencode(app_datetime($urow['Fecha_Prestamo'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Devolucion)%%>', app_datetime($row['Fecha_Devolucion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Devolucion)%%>', urlencode(app_datetime($urow['Fecha_Devolucion'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Estado_prestamo)%%>', safe_html($urow['id_Estado_prestamo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Estado_prestamo)%%>', html_attr($row['id_Estado_prestamo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Estado_prestamo)%%>', urlencode($urow['id_Estado_prestamo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cantidad)%%>', safe_html($urow['Cantidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cantidad)%%>', html_attr($row['Cantidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cantidad)%%>', urlencode($urow['Cantidad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', safe_html($urow['Cod_Ejemplar']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', html_attr($row['Cod_Ejemplar']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode($urow['Cod_Ejemplar']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Usuario)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Usuario)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_usuario)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Politica_pretamo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Politica_pretamo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_documento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Libro_Prestado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Libro_Prestado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Prestamo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Prestamo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Fecha_Devolucion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Fecha_Devolucion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Estado_prestamo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Estado_prestamo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cantidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cantidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tid_Usuario_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Circulacion_autofill.php?rnd1=$rnd1&mfk=id_Usuario&id=' + encodeURIComponent('".addslashes($row['id_Usuario'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Circulacion_autofill.php?rnd1=$rnd1&mfk=id_Usuario&id=' + encodeURIComponent(AppGini.current_id_Usuario{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#id_Usuario$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#id_Usuario$rnd1').prop('disabled', false); " : "\$j('#id_Usuario$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#id_Usuario_caption').length) \$j('#id_Usuario_caption').click(function() { id_Usuario_update_autofills$rnd1(); });\n";

	$templateCode .= "\tLibro_Prestado_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Circulacion_autofill.php?rnd1=$rnd1&mfk=Libro_Prestado&id=' + encodeURIComponent('".addslashes($row['Libro_Prestado'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Circulacion_autofill.php?rnd1=$rnd1&mfk=Libro_Prestado&id=' + encodeURIComponent(AppGini.current_Libro_Prestado{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Libro_Prestado$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm['insert'] || (($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3)) ? "\$j('#Libro_Prestado$rnd1').prop('disabled', false); " : "\$j('#Libro_Prestado$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Libro_Prestado_caption').length) \$j('#Libro_Prestado_caption').click(function() { Libro_Prestado_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Circulacion');
	if($selected_id) {
		$jdata = get_joined_record('Circulacion', $selected_id);
		if($jdata === false) $jdata = get_defaults('Circulacion');
		$rdata = $row;
	}
	$templateCode .= loadView('Circulacion-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Circulacion_dv
	if(function_exists('Circulacion_dv')) {
		$args = [];
		Circulacion_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}