<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Itemes.php');
	include_once(__DIR__ . '/Itemes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Itemes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Itemes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Itemes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Cod item */" => "Cod_item",
		"IF(    CHAR_LENGTH(`Estado_Conservacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Conservacion1`.`Descripcion`), '') /* Estado Conservacion */" => "Estado_Conservacion",
		"`Itemes`.`Num_Copia`" => "Num_Copia",
		"`Itemes`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Itemes`.`Estado_de_Baja`" => "Estado_de_Baja",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Itemes`.`id`',
		2 => '`Catalogo1`.`Item`',
		3 => '`Estado_Conservacion1`.`Descripcion`',
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Itemes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Cod item */" => "Cod_item",
		"IF(    CHAR_LENGTH(`Estado_Conservacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Conservacion1`.`Descripcion`), '') /* Estado Conservacion */" => "Estado_Conservacion",
		"`Itemes`.`Num_Copia`" => "Num_Copia",
		"`Itemes`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Itemes`.`Estado_de_Baja`" => "Estado_de_Baja",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Itemes`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Cod item */" => "Cod item",
		"IF(    CHAR_LENGTH(`Estado_Conservacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Conservacion1`.`Descripcion`), '') /* Estado Conservacion */" => "Estado Conservacion",
		"`Itemes`.`Num_Copia`" => "Num Copia",
		"`Itemes`.`Cod_Ejemplar`" => "Cod Ejemplar",
		"`Itemes`.`Estado_de_Baja`" => "Estado de Baja",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Itemes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Catalogo1`.`Item`), CONCAT_WS('',   `Catalogo1`.`Item`), '') /* Cod item */" => "Cod_item",
		"IF(    CHAR_LENGTH(`Estado_Conservacion1`.`Descripcion`), CONCAT_WS('',   `Estado_Conservacion1`.`Descripcion`), '') /* Estado Conservacion */" => "Estado_Conservacion",
		"`Itemes`.`Num_Copia`" => "Num_Copia",
		"`Itemes`.`Cod_Ejemplar`" => "Cod_Ejemplar",
		"`Itemes`.`Estado_de_Baja`" => "Estado_de_Baja",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Cod_item' => 'Cod item', 'Estado_Conservacion' => 'Estado Conservacion', ];

	$x->QueryFrom = "`Itemes` LEFT JOIN `Catalogo` as Catalogo1 ON `Catalogo1`.`id`=`Itemes`.`Cod_item` LEFT JOIN `Estado_Conservacion` as Estado_Conservacion1 ON `Estado_Conservacion1`.`id`=`Itemes`.`Estado_Conservacion` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Itemes_view.php';
	$x->TableTitle = 'Itemes';
	$x->TableIcon = 'resources/table_icons/book_add.png';
	$x->PrimaryKey = '`Itemes`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Cod item', 'Estado Conservacion', 'Num Copia', 'Cod Ejemplar', 'Estado de Baja', ];
	$x->ColFieldName = ['Cod_item', 'Estado_Conservacion', 'Num_Copia', 'Cod_Ejemplar', 'Estado_de_Baja', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Itemes_templateTV.html';
	$x->SelectedTemplate = 'templates/Itemes_templateTVS.html';
	$x->TemplateDV = 'templates/Itemes_templateDV.html';
	$x->TemplateDVP = 'templates/Itemes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Itemes_init
	$render = true;
	if(function_exists('Itemes_init')) {
		$args = [];
		$render = Itemes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Itemes_header
	$headerCode = '';
	if(function_exists('Itemes_header')) {
		$args = [];
		$headerCode = Itemes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Itemes_footer
	$footerCode = '';
	if(function_exists('Itemes_footer')) {
		$args = [];
		$footerCode = Itemes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
