<?php

// Data functions (insert, update, delete, form) for table Itemes

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function Itemes_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Itemes');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Cod_item' => Request::lookup('Cod_item', ''),
		'Estado_Conservacion' => Request::lookup('Estado_Conservacion', ''),
		'Num_Copia' => Request::val('Num_Copia', ''),
		'Cod_Ejemplar' => Request::val('Cod_Ejemplar', ''),
		'Estado_de_Baja' => Request::val('Estado_de_Baja', ''),
	];


	// hook: Itemes_before_insert
	if(function_exists('Itemes_before_insert')) {
		$args = [];
		if(!Itemes_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Itemes', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Itemes', $recID, calculated_fields()['Itemes']);

	// hook: Itemes_after_insert
	if(function_exists('Itemes_after_insert')) {
		$res = sql("SELECT * FROM `Itemes` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Itemes_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Itemes', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Itemes_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Itemes_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Itemes_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Itemes', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Itemes_before_delete
	if(function_exists('Itemes_before_delete')) {
		$args = [];
		if(!Itemes_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Circulacion
	$res = sql("SELECT `id` FROM `Itemes` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Circulacion` WHERE `Cod_Ejemplar`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Itemes_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Itemes_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Itemes` WHERE `id`='{$selected_id}'", $eo);

	// hook: Itemes_after_delete
	if(function_exists('Itemes_after_delete')) {
		$args = [];
		Itemes_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Itemes' AND `pkValue`='{$selected_id}'", $eo);
}

function Itemes_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Itemes', $selected_id, 'edit')) return false;

	$data = [
		'Cod_item' => Request::lookup('Cod_item', ''),
		'Estado_Conservacion' => Request::lookup('Estado_Conservacion', ''),
		'Num_Copia' => Request::val('Num_Copia', ''),
		'Cod_Ejemplar' => Request::val('Cod_Ejemplar', ''),
		'Estado_de_Baja' => Request::val('Estado_de_Baja', ''),
	];

	// get existing values
	$old_data = getRecord('Itemes', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Itemes_before_update
	if(function_exists('Itemes_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Itemes_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Itemes', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Itemes_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Itemes', $data['selectedID'], calculated_fields()['Itemes']);

	// hook: Itemes_after_update
	if(function_exists('Itemes_after_update')) {
		$res = sql("SELECT * FROM `Itemes` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Itemes_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Itemes' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Itemes_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Itemes');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_Cod_item = Request::val('filterer_Cod_item');
	$filterer_Estado_Conservacion = Request::val('filterer_Estado_Conservacion');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Cod_item
	$combo_Cod_item = new DataCombo;
	// combobox: Estado_Conservacion
	$combo_Estado_Conservacion = new DataCombo;
	// combobox: Estado_de_Baja
	$combo_Estado_de_Baja = new Combo;
	$combo_Estado_de_Baja->ListType = 0;
	$combo_Estado_de_Baja->MultipleSeparator = ', ';
	$combo_Estado_de_Baja->ListBoxHeight = 10;
	$combo_Estado_de_Baja->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Itemes.Estado_de_Baja.csv')) {
		$Estado_de_Baja_data = addslashes(implode('', @file(__DIR__ . '/hooks/Itemes.Estado_de_Baja.csv')));
		$combo_Estado_de_Baja->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Estado_de_Baja_data))));
		$combo_Estado_de_Baja->ListData = $combo_Estado_de_Baja->ListItem;
	} else {
		$combo_Estado_de_Baja->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("S&#237;;;No"))));
		$combo_Estado_de_Baja->ListData = $combo_Estado_de_Baja->ListItem;
	}
	$combo_Estado_de_Baja->SelectName = 'Estado_de_Baja';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Itemes' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Itemes' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Itemes` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Itemes_view.php', false);
		}
		$combo_Cod_item->SelectedData = $row['Cod_item'];
		$combo_Estado_Conservacion->SelectedData = $row['Estado_Conservacion'];
		$combo_Estado_de_Baja->SelectedData = $row['Estado_de_Baja'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Cod_item->SelectedData = $filterer_Cod_item;
		$combo_Estado_Conservacion->SelectedData = $filterer_Estado_Conservacion;
		$combo_Estado_de_Baja->SelectedText = (isset($filterField[1]) && $filterField[1] == '6' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_Cod_item->HTML = '<span id="Cod_item-container' . $rnd1 . '"></span><input type="hidden" name="Cod_item" id="Cod_item' . $rnd1 . '" value="' . html_attr($combo_Cod_item->SelectedData) . '">';
	$combo_Cod_item->MatchText = '<span id="Cod_item-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Cod_item" id="Cod_item' . $rnd1 . '" value="' . html_attr($combo_Cod_item->SelectedData) . '">';
	$combo_Estado_Conservacion->HTML = '<span id="Estado_Conservacion-container' . $rnd1 . '"></span><input type="hidden" name="Estado_Conservacion" id="Estado_Conservacion' . $rnd1 . '" value="' . html_attr($combo_Estado_Conservacion->SelectedData) . '">';
	$combo_Estado_Conservacion->MatchText = '<span id="Estado_Conservacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Estado_Conservacion" id="Estado_Conservacion' . $rnd1 . '" value="' . html_attr($combo_Estado_Conservacion->SelectedData) . '">';
	$combo_Estado_de_Baja->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Cod_item__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Cod_item'] : htmlspecialchars($filterer_Cod_item, ENT_QUOTES)); ?>"};
		AppGini.current_Estado_Conservacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Estado_Conservacion'] : htmlspecialchars($filterer_Estado_Conservacion, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Cod_item_reload__RAND__) == 'function') Cod_item_reload__RAND__();
				if(typeof(Estado_Conservacion_reload__RAND__) == 'function') Estado_Conservacion_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Cod_item_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Cod_item-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Cod_item__RAND__.value, t: 'Itemes', f: 'Cod_item' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Cod_item"]').val(resp.results[0].id);
							$j('[id=Cod_item-container-readonly__RAND__]').html('<span class="match-text" id="Cod_item-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }


							if(typeof(Cod_item_update_autofills__RAND__) == 'function') Cod_item_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Itemes', f: 'Cod_item' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Cod_item__RAND__.value = e.added.id;
				AppGini.current_Cod_item__RAND__.text = e.added.text;
				$j('[name="Cod_item"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }


				if(typeof(Cod_item_update_autofills__RAND__) == 'function') Cod_item_update_autofills__RAND__();
			});

			if(!$j("#Cod_item-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Cod_item__RAND__.value, t: 'Itemes', f: 'Cod_item' },
					success: function(resp) {
						$j('[name="Cod_item"]').val(resp.results[0].id);
						$j('[id=Cod_item-container-readonly__RAND__]').html('<span class="match-text" id="Cod_item-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }

						if(typeof(Cod_item_update_autofills__RAND__) == 'function') Cod_item_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Cod_item__RAND__.value, t: 'Itemes', f: 'Cod_item' },
				success: function(resp) {
					$j('[id=Cod_item-container__RAND__], [id=Cod_item-container-readonly__RAND__]').html('<span class="match-text" id="Cod_item-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Catalogo_view_parent]').hide(); } else { $j('.btn[id=Catalogo_view_parent]').show(); }

					if(typeof(Cod_item_update_autofills__RAND__) == 'function') Cod_item_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Estado_Conservacion_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Estado_Conservacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Estado_Conservacion__RAND__.value, t: 'Itemes', f: 'Estado_Conservacion' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Estado_Conservacion"]').val(resp.results[0].id);
							$j('[id=Estado_Conservacion-container-readonly__RAND__]').html('<span class="match-text" id="Estado_Conservacion-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Conservacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Conservacion_view_parent]').show(); }


							if(typeof(Estado_Conservacion_update_autofills__RAND__) == 'function') Estado_Conservacion_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Itemes', f: 'Estado_Conservacion' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Estado_Conservacion__RAND__.value = e.added.id;
				AppGini.current_Estado_Conservacion__RAND__.text = e.added.text;
				$j('[name="Estado_Conservacion"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Conservacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Conservacion_view_parent]').show(); }


				if(typeof(Estado_Conservacion_update_autofills__RAND__) == 'function') Estado_Conservacion_update_autofills__RAND__();
			});

			if(!$j("#Estado_Conservacion-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Estado_Conservacion__RAND__.value, t: 'Itemes', f: 'Estado_Conservacion' },
					success: function(resp) {
						$j('[name="Estado_Conservacion"]').val(resp.results[0].id);
						$j('[id=Estado_Conservacion-container-readonly__RAND__]').html('<span class="match-text" id="Estado_Conservacion-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Conservacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Conservacion_view_parent]').show(); }

						if(typeof(Estado_Conservacion_update_autofills__RAND__) == 'function') Estado_Conservacion_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Estado_Conservacion__RAND__.value, t: 'Itemes', f: 'Estado_Conservacion' },
				success: function(resp) {
					$j('[id=Estado_Conservacion-container__RAND__], [id=Estado_Conservacion-container-readonly__RAND__]').html('<span class="match-text" id="Estado_Conservacion-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estado_Conservacion_view_parent]').hide(); } else { $j('.btn[id=Estado_Conservacion_view_parent]').show(); }

					if(typeof(Estado_Conservacion_update_autofills__RAND__) == 'function') Estado_Conservacion_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Itemes_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Itemes_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Iteme details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Itemes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Itemes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Itemes_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Cod_item').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Cod_item_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Estado_Conservacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Estado_Conservacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Num_Copia').replaceWith('<div class=\"form-control-static\" id=\"Num_Copia\">' + (jQuery('#Num_Copia').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Cod_Ejemplar').replaceWith('<div class=\"form-control-static\" id=\"Cod_Ejemplar\">' + (jQuery('#Cod_Ejemplar').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Estado_de_Baja').replaceWith('<div class=\"form-control-static\" id=\"Estado_de_Baja\">' + (jQuery('#Estado_de_Baja').val() || '') + '</div>'); jQuery('#Estado_de_Baja-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Cod_item)%%>', $combo_Cod_item->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Cod_item)%%>', $combo_Cod_item->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Cod_item)%%>', urlencode($combo_Cod_item->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Estado_Conservacion)%%>', $combo_Estado_Conservacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Estado_Conservacion)%%>', $combo_Estado_Conservacion->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Estado_Conservacion)%%>', urlencode($combo_Estado_Conservacion->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Estado_de_Baja)%%>', $combo_Estado_de_Baja->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Estado_de_Baja)%%>', $combo_Estado_de_Baja->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Cod_item' => ['Catalogo', 'Cod item'], 'Estado_Conservacion' => ['Estado_Conservacion', 'Estado Conservacion'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cod_item)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Estado_Conservacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Num_Copia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cod_Ejemplar)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Estado_de_Baja)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cod_item)%%>', safe_html($urow['Cod_item']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cod_item)%%>', html_attr($row['Cod_item']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_item)%%>', urlencode($urow['Cod_item']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Estado_Conservacion)%%>', safe_html($urow['Estado_Conservacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Estado_Conservacion)%%>', html_attr($row['Estado_Conservacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado_Conservacion)%%>', urlencode($urow['Estado_Conservacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Num_Copia)%%>', safe_html($urow['Num_Copia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Num_Copia)%%>', html_attr($row['Num_Copia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Num_Copia)%%>', urlencode($urow['Num_Copia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', safe_html($urow['Cod_Ejemplar']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', html_attr($row['Cod_Ejemplar']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode($urow['Cod_Ejemplar']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Estado_de_Baja)%%>', safe_html($urow['Estado_de_Baja']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Estado_de_Baja)%%>', html_attr($row['Estado_de_Baja']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado_de_Baja)%%>', urlencode($urow['Estado_de_Baja']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cod_item)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_item)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Estado_Conservacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado_Conservacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Num_Copia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Num_Copia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cod_Ejemplar)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cod_Ejemplar)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Estado_de_Baja)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado_de_Baja)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Itemes');
	if($selected_id) {
		$jdata = get_joined_record('Itemes', $selected_id);
		if($jdata === false) $jdata = get_defaults('Itemes');
		$rdata = $row;
	}
	$templateCode .= loadView('Itemes-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Itemes_dv
	if(function_exists('Itemes_dv')) {
		$args = [];
		Itemes_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}