<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Politica_de_Prestamos.php');
	include_once(__DIR__ . '/Politica_de_Prestamos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Politica_de_Prestamos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Politica_de_Prestamos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Politica_de_Prestamos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"`Politica_de_Prestamos`.`Duracion_Prestamo`" => "Duracion_Prestamo",
		"`Politica_de_Prestamos`.`Lim_Doc_Presado`" => "Lim_Doc_Presado",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Politica_de_Prestamos`.`id`',
		2 => '`Tipo_Usuario1`.`Descripcion`',
		3 => '`Tipo_Documento1`.`Descripcion`',
		4 => '`Politica_de_Prestamos`.`Duracion_Prestamo`',
		5 => '`Politica_de_Prestamos`.`Lim_Doc_Presado`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Politica_de_Prestamos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"`Politica_de_Prestamos`.`Duracion_Prestamo`" => "Duracion_Prestamo",
		"`Politica_de_Prestamos`.`Lim_Doc_Presado`" => "Lim_Doc_Presado",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Politica_de_Prestamos`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "Tipo de Usuario",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "Tipo de documento",
		"`Politica_de_Prestamos`.`Duracion_Prestamo`" => "Duracion del Pr&#233;stamo",
		"`Politica_de_Prestamos`.`Lim_Doc_Presado`" => "L&#237;mite de Doc_Prestado",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Politica_de_Prestamos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Tipo_Usuario1`.`Descripcion`), CONCAT_WS('',   `Tipo_Usuario1`.`Descripcion`), '') /* Tipo de Usuario */" => "id_Tipo_usuario",
		"IF(    CHAR_LENGTH(`Tipo_Documento1`.`Descripcion`), CONCAT_WS('',   `Tipo_Documento1`.`Descripcion`), '') /* Tipo de documento */" => "id_Tipo_documento",
		"`Politica_de_Prestamos`.`Duracion_Prestamo`" => "Duracion_Prestamo",
		"`Politica_de_Prestamos`.`Lim_Doc_Presado`" => "Lim_Doc_Presado",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_Tipo_usuario' => 'Tipo de Usuario', 'id_Tipo_documento' => 'Tipo de documento', ];

	$x->QueryFrom = "`Politica_de_Prestamos` LEFT JOIN `Tipo_Usuario` as Tipo_Usuario1 ON `Tipo_Usuario1`.`id`=`Politica_de_Prestamos`.`id_Tipo_usuario` LEFT JOIN `Tipo_Documento` as Tipo_Documento1 ON `Tipo_Documento1`.`id`=`Politica_de_Prestamos`.`id_Tipo_documento` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Politica_de_Prestamos_view.php';
	$x->TableTitle = 'Politica de Prestamos';
	$x->TableIcon = 'resources/table_icons/accept.png';
	$x->PrimaryKey = '`Politica_de_Prestamos`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo de Usuario', 'Tipo de documento', 'Duracion del Pr&#233;stamo', 'L&#237;mite de Doc_Prestado', ];
	$x->ColFieldName = ['id_Tipo_usuario', 'id_Tipo_documento', 'Duracion_Prestamo', 'Lim_Doc_Presado', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Politica_de_Prestamos_templateTV.html';
	$x->SelectedTemplate = 'templates/Politica_de_Prestamos_templateTVS.html';
	$x->TemplateDV = 'templates/Politica_de_Prestamos_templateDV.html';
	$x->TemplateDVP = 'templates/Politica_de_Prestamos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Politica_de_Prestamos_init
	$render = true;
	if(function_exists('Politica_de_Prestamos_init')) {
		$args = [];
		$render = Politica_de_Prestamos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Politica_de_Prestamos_header
	$headerCode = '';
	if(function_exists('Politica_de_Prestamos_header')) {
		$args = [];
		$headerCode = Politica_de_Prestamos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Politica_de_Prestamos_footer
	$footerCode = '';
	if(function_exists('Politica_de_Prestamos_footer')) {
		$args = [];
		$footerCode = Politica_de_Prestamos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
