<?php

// Data functions (insert, update, delete, form) for table Politica_de_Prestamos

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function Politica_de_Prestamos_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Politica_de_Prestamos');
	if(!$arrPerm['insert']) return false;

	$data = [
		'id_Tipo_usuario' => Request::lookup('id_Tipo_usuario', ''),
		'id_Tipo_documento' => Request::lookup('id_Tipo_documento', ''),
		'Duracion_Prestamo' => Request::val('Duracion_Prestamo', ''),
		'Lim_Doc_Presado' => Request::val('Lim_Doc_Presado', ''),
	];


	// hook: Politica_de_Prestamos_before_insert
	if(function_exists('Politica_de_Prestamos_before_insert')) {
		$args = [];
		if(!Politica_de_Prestamos_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Politica_de_Prestamos', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Politica_de_Prestamos', $recID, calculated_fields()['Politica_de_Prestamos']);

	// hook: Politica_de_Prestamos_after_insert
	if(function_exists('Politica_de_Prestamos_after_insert')) {
		$res = sql("SELECT * FROM `Politica_de_Prestamos` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Politica_de_Prestamos_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Politica_de_Prestamos', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Politica_de_Prestamos_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Politica_de_Prestamos_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Politica_de_Prestamos_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Politica_de_Prestamos', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Politica_de_Prestamos_before_delete
	if(function_exists('Politica_de_Prestamos_before_delete')) {
		$args = [];
		if(!Politica_de_Prestamos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Circulacion
	$res = sql("SELECT `id` FROM `Politica_de_Prestamos` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Circulacion` WHERE `id_Politica_pretamo`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Circulacion', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Politica_de_Prestamos_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Politica_de_Prestamos_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Politica_de_Prestamos` WHERE `id`='{$selected_id}'", $eo);

	// hook: Politica_de_Prestamos_after_delete
	if(function_exists('Politica_de_Prestamos_after_delete')) {
		$args = [];
		Politica_de_Prestamos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Politica_de_Prestamos' AND `pkValue`='{$selected_id}'", $eo);
}

function Politica_de_Prestamos_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Politica_de_Prestamos', $selected_id, 'edit')) return false;

	$data = [
		'id_Tipo_usuario' => Request::lookup('id_Tipo_usuario', ''),
		'id_Tipo_documento' => Request::lookup('id_Tipo_documento', ''),
		'Duracion_Prestamo' => Request::val('Duracion_Prestamo', ''),
		'Lim_Doc_Presado' => Request::val('Lim_Doc_Presado', ''),
	];

	// get existing values
	$old_data = getRecord('Politica_de_Prestamos', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Politica_de_Prestamos_before_update
	if(function_exists('Politica_de_Prestamos_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Politica_de_Prestamos_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Politica_de_Prestamos', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Politica_de_Prestamos_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Politica_de_Prestamos', $data['selectedID'], calculated_fields()['Politica_de_Prestamos']);

	// hook: Politica_de_Prestamos_after_update
	if(function_exists('Politica_de_Prestamos_after_update')) {
		$res = sql("SELECT * FROM `Politica_de_Prestamos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Politica_de_Prestamos_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Politica_de_Prestamos' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Politica_de_Prestamos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Politica_de_Prestamos');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_id_Tipo_usuario = Request::val('filterer_id_Tipo_usuario');
	$filterer_id_Tipo_documento = Request::val('filterer_id_Tipo_documento');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: id_Tipo_usuario
	$combo_id_Tipo_usuario = new DataCombo;
	// combobox: id_Tipo_documento
	$combo_id_Tipo_documento = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Politica_de_Prestamos' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Politica_de_Prestamos' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Politica_de_Prestamos` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Politica_de_Prestamos_view.php', false);
		}
		$combo_id_Tipo_usuario->SelectedData = $row['id_Tipo_usuario'];
		$combo_id_Tipo_documento->SelectedData = $row['id_Tipo_documento'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_id_Tipo_usuario->SelectedData = $filterer_id_Tipo_usuario;
		$combo_id_Tipo_documento->SelectedData = $filterer_id_Tipo_documento;
	}
	$combo_id_Tipo_usuario->HTML = '<span id="id_Tipo_usuario-container' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_usuario" id="id_Tipo_usuario' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_usuario->SelectedData) . '">';
	$combo_id_Tipo_usuario->MatchText = '<span id="id_Tipo_usuario-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_usuario" id="id_Tipo_usuario' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_usuario->SelectedData) . '">';
	$combo_id_Tipo_documento->HTML = '<span id="id_Tipo_documento-container' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_documento" id="id_Tipo_documento' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_documento->SelectedData) . '">';
	$combo_id_Tipo_documento->MatchText = '<span id="id_Tipo_documento-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_Tipo_documento" id="id_Tipo_documento' . $rnd1 . '" value="' . html_attr($combo_id_Tipo_documento->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_id_Tipo_usuario__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Tipo_usuario'] : htmlspecialchars($filterer_id_Tipo_usuario, ENT_QUOTES)); ?>"};
		AppGini.current_id_Tipo_documento__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_Tipo_documento'] : htmlspecialchars($filterer_id_Tipo_documento, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(id_Tipo_usuario_reload__RAND__) == 'function') id_Tipo_usuario_reload__RAND__();
				if(typeof(id_Tipo_documento_reload__RAND__) == 'function') id_Tipo_documento_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function id_Tipo_usuario_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Tipo_usuario-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_usuario' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Tipo_usuario"]').val(resp.results[0].id);
							$j('[id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }


							if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Politica_de_Prestamos', f: 'id_Tipo_usuario' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Tipo_usuario__RAND__.value = e.added.id;
				AppGini.current_id_Tipo_usuario__RAND__.text = e.added.text;
				$j('[name="id_Tipo_usuario"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }


				if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
			});

			if(!$j("#id_Tipo_usuario-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_usuario' },
					success: function(resp) {
						$j('[name="id_Tipo_usuario"]').val(resp.results[0].id);
						$j('[id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }

						if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Tipo_usuario__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_usuario' },
				success: function(resp) {
					$j('[id=id_Tipo_usuario-container__RAND__], [id=id_Tipo_usuario-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_usuario-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Usuario_view_parent]').hide(); } else { $j('.btn[id=Tipo_Usuario_view_parent]').show(); }

					if(typeof(id_Tipo_usuario_update_autofills__RAND__) == 'function') id_Tipo_usuario_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_Tipo_documento_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_Tipo_documento-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_documento' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_Tipo_documento"]').val(resp.results[0].id);
							$j('[id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


							if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Politica_de_Prestamos', f: 'id_Tipo_documento' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_Tipo_documento__RAND__.value = e.added.id;
				AppGini.current_id_Tipo_documento__RAND__.text = e.added.text;
				$j('[name="id_Tipo_documento"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }


				if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
			});

			if(!$j("#id_Tipo_documento-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_documento' },
					success: function(resp) {
						$j('[name="id_Tipo_documento"]').val(resp.results[0].id);
						$j('[id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

						if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_Tipo_documento__RAND__.value, t: 'Politica_de_Prestamos', f: 'id_Tipo_documento' },
				success: function(resp) {
					$j('[id=id_Tipo_documento-container__RAND__], [id=id_Tipo_documento-container-readonly__RAND__]').html('<span class="match-text" id="id_Tipo_documento-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Tipo_Documento_view_parent]').hide(); } else { $j('.btn[id=Tipo_Documento_view_parent]').show(); }

					if(typeof(id_Tipo_documento_update_autofills__RAND__) == 'function') id_Tipo_documento_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Politica_de_Prestamos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Politica_de_Prestamos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Politica de Prestamo details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Politica_de_Prestamos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Politica_de_Prestamos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Politica_de_Prestamos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#id_Tipo_usuario').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_usuario_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_documento').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_Tipo_documento_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Duracion_Prestamo').replaceWith('<div class=\"form-control-static\" id=\"Duracion_Prestamo\">' + (jQuery('#Duracion_Prestamo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Lim_Doc_Presado').replaceWith('<div class=\"form-control-static\" id=\"Lim_Doc_Presado\">' + (jQuery('#Lim_Doc_Presado').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(id_Tipo_usuario)%%>', $combo_id_Tipo_usuario->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Tipo_usuario)%%>', $combo_id_Tipo_usuario->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Tipo_usuario)%%>', urlencode($combo_id_Tipo_usuario->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_Tipo_documento)%%>', $combo_id_Tipo_documento->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_Tipo_documento)%%>', $combo_id_Tipo_documento->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_Tipo_documento)%%>', urlencode($combo_id_Tipo_documento->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['id_Tipo_usuario' => ['Tipo_Usuario', 'Tipo de Usuario'], 'id_Tipo_documento' => ['Tipo_Documento', 'Tipo de documento'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Tipo_usuario)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_Tipo_documento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Duracion_Prestamo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Lim_Doc_Presado)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', safe_html($urow['id_Tipo_usuario']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', html_attr($row['id_Tipo_usuario']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_usuario)%%>', urlencode($urow['id_Tipo_usuario']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', safe_html($urow['id_Tipo_documento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', html_attr($row['id_Tipo_documento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_documento)%%>', urlencode($urow['id_Tipo_documento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Duracion_Prestamo)%%>', safe_html($urow['Duracion_Prestamo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Duracion_Prestamo)%%>', html_attr($row['Duracion_Prestamo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Duracion_Prestamo)%%>', urlencode($urow['Duracion_Prestamo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Lim_Doc_Presado)%%>', safe_html($urow['Lim_Doc_Presado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Lim_Doc_Presado)%%>', html_attr($row['Lim_Doc_Presado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lim_Doc_Presado)%%>', urlencode($urow['Lim_Doc_Presado']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Tipo_usuario)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_usuario)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_Tipo_documento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_Tipo_documento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Duracion_Prestamo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Duracion_Prestamo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Lim_Doc_Presado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Lim_Doc_Presado)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Politica_de_Prestamos');
	if($selected_id) {
		$jdata = get_joined_record('Politica_de_Prestamos', $selected_id);
		if($jdata === false) $jdata = get_defaults('Politica_de_Prestamos');
		$rdata = $row;
	}
	$templateCode .= loadView('Politica_de_Prestamos-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Politica_de_Prestamos_dv
	if(function_exists('Politica_de_Prestamos_dv')) {
		$args = [];
		Politica_de_Prestamos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}