<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Tipo_Autoridad.php');
	include_once(__DIR__ . '/Tipo_Autoridad_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Tipo_Autoridad');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Tipo_Autoridad';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Tipo_Autoridad`.`id`" => "id",
		"`Tipo_Autoridad`.`Descripcion`" => "Descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Tipo_Autoridad`.`id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Tipo_Autoridad`.`id`" => "id",
		"`Tipo_Autoridad`.`Descripcion`" => "Descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Tipo_Autoridad`.`id`" => "ID",
		"`Tipo_Autoridad`.`Descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Tipo_Autoridad`.`id`" => "id",
		"`Tipo_Autoridad`.`Descripcion`" => "Descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Tipo_Autoridad` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Tipo_Autoridad_view.php';
	$x->TableTitle = 'Tipo Autoridad';
	$x->TableIcon = 'resources/table_icons/user_edit.png';
	$x->PrimaryKey = '`Tipo_Autoridad`.`id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Descripcion', ];
	$x->ColFieldName = ['Descripcion', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Tipo_Autoridad_templateTV.html';
	$x->SelectedTemplate = 'templates/Tipo_Autoridad_templateTVS.html';
	$x->TemplateDV = 'templates/Tipo_Autoridad_templateDV.html';
	$x->TemplateDVP = 'templates/Tipo_Autoridad_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Tipo_Autoridad_init
	$render = true;
	if(function_exists('Tipo_Autoridad_init')) {
		$args = [];
		$render = Tipo_Autoridad_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Tipo_Autoridad_header
	$headerCode = '';
	if(function_exists('Tipo_Autoridad_header')) {
		$args = [];
		$headerCode = Tipo_Autoridad_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Tipo_Autoridad_footer
	$footerCode = '';
	if(function_exists('Tipo_Autoridad_footer')) {
		$args = [];
		$footerCode = Tipo_Autoridad_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
